In [7]:
import pandas as pd

In [8]:
# countinb the number of minio images
from pathlib import Path

In [9]:
list(Path("images/").glob("*/*minio*"))

[PosixPath('images/2581/8.png.part.minio'),
 PosixPath('images/2076/7.png.part.minio'),
 PosixPath('images/2778/2.png.part.minio'),
 PosixPath('images/373/8.png.part.minio'),
 PosixPath('images/2702/8.png.part.minio'),
 PosixPath('images/2557/8.png.part.minio'),
 PosixPath('images/2606/10.png.part.minio')]

In [10]:
# small subset of images that are missing as baseline

In [11]:
failed = pd.read_csv("failed.csv")

In [12]:
failed

,missing_image,figure_id,url
0,img-09125,9124,https://data.cyverse.org/dav-anon/iplant/home/...
1,img-09126,9125,https://data.cyverse.org/dav-anon/iplant/home/...
2,img-09127,9126,https://data.cyverse.org/dav-anon/iplant/home/...
3,img-09128,9127,https://data.cyverse.org/dav-anon/iplant/home/...
4,img-09129,9128,https://data.cyverse.org/dav-anon/iplant/home/...
...,...,...,...
1575,img-35020,35019,https://data.cyverse.org/dav-anon/iplant/home/...
1576,img-35021,35020,https://data.cyverse.org/dav-anon/iplant/home/...
1577,img-35022,35021,https://data.cyverse.org/dav-anon/iplant/home/...
1578,img-35023,35022,https://data.cyverse.org/dav-anon/iplant/home/...
1579,img-35024,35023,https://data.cyverse.org/dav-anon/iplant/home/...

In [13]:
failed["stem"] = [Path(e.url).stem for i,e in failed.iterrows()]

In [14]:
failed

,missing_image,figure_id,url,stem
0,img-09125,9124,https://data.cyverse.org/dav-anon/iplant/home/...,2076_7000_0
1,img-09126,9125,https://data.cyverse.org/dav-anon/iplant/home/...,2076_8000_0
2,img-09127,9126,https://data.cyverse.org/dav-anon/iplant/home/...,2076_8000_1
3,img-09128,9127,https://data.cyverse.org/dav-anon/iplant/home/...,2076_9000_0
4,img-09129,9128,https://data.cyverse.org/dav-anon/iplant/home/...,2076_9000_1
...,...,...,...,...
1575,img-35020,35019,https://data.cyverse.org/dav-anon/iplant/home/...,937_0000_0
1576,img-35021,35020,https://data.cyverse.org/dav-anon/iplant/home/...,937_1000_0
1577,img-35022,35021,https://data.cyverse.org/dav-anon/iplant/home/...,937_2000_0
1578,img-35023,35022,https://data.cyverse.org/dav-anon/iplant/home/...,937_4000_0
1579,img-35024,35023,https://data.cyverse.org/dav-anon/iplant/home/...,937_5000_0

In [15]:
from pathlib import Path

In [16]:
'20000'.rstrip("0")

'2'

In [17]:
# the code needs to know whether we are after image 20, or image 2 for instance, rstriping out the 0s isn't really a good solution

In [19]:
for i,row in failed.iterrows():
    if i>10:
        break
    im_url = row.url
    tail = Path(im_url).stem
    parts = tail.split("_")
    
    print(Path(f"./subfigures/{tail}.png/"))

subfigures/2076_7000_0.png
subfigures/2076_8000_0.png
subfigures/2076_8000_1.png
subfigures/2076_9000_0.png
subfigures/2076_9000_1.png
subfigures/2076_9000_2.png
subfigures/2076_9000_3.png
subfigures/2076_9000_4.png
subfigures/2076_9000_5.png
subfigures/2076_9000_6.png
subfigures/2076_9000_7.png

In [20]:
import json

In [21]:
annot = json.loads(Path("./annotation.json").read_text())

In [22]:
annot["2076"]

[{'image_id': 0,
  'file_name': '2076_00.png',
  'page': 0,
  'dpi': 300,
  'bbox': [0.1016949152542373,
   0.1631201514902041,
   0.9194915254237288,
   0.4688372093023256],
  'visualization_bbox': {'bar_chart': [[12.384408479923593,
     24.48294688172252,
     1903.833333333333,
     986.0]],
   'small_multiple': [[10.41927070413891,
     26.448084657507223,
     1901.9444444444443,
     986.0]]},
  'nums_of_visualizations': {'bar_chart': 1, 'small_multiple': 1},
  'caption': 'Fig. 1. BallotMap showing electoral success (or otherwise) of each candidate for the three main parties in wards (small rectangles) in each London borough (grid squares) in the 2010 local government elections. Vertical ordering of candidates within each borough is by ballot paper position within party (top row ﬁrst, middle row second, bottom row third). Main parties with three candidates in a ward are shown. If no ballot ordering bias existed there would be no systematic structure to bar lengths. This ballotMap shows that more candidates get elected who are listed ﬁrst within their party than do candidates who are second or third.'},
 {'image_id': 1,
  'file_name': '2076_01.png',
  'page': 1,
  'dpi': 300,
  'bbox': [0.5466101694915254,
   0.054593019707258356,
   0.9088983050847458,
   0.598139534883721],
  'visualization_bbox': {'table': [[50.19827586206907,
     26.865884369817273,
     696.6994645247655,
     1743.6131191432396]]},
  'nums_of_visualizations': {'table': 1},
  'caption': 'Fig. 2. Sample ballot paper from the London May 2010 local election showing alphabetic arrangement of ﬁctitious candidates on the page. Each voter can vote for up to three candidates on the ballot paper (order of preference not indicated).'},
 {'image_id': 2,
  'file_name': '2076_02.png',
  'page': 2,
  'dpi': 300,
  'bbox': [0.5279187817258884,
   0.11162790697674418,
   0.949238578680203,
   0.17488372093023255],
  'visualization_bbox': {'table': [[4.349344978165939,
     4.76107298814722,
     991.650655021834,
     199.23892701185278]]},
  'nums_of_visualizations': {'table': 1},
  'caption': 'Table 1. Primary candidate variables extracted from the London  DataStore and OS Boundary-Line datasets'},
 {'image_id': 3,
  'file_name': '2076_03.png',
  'page': 2,
  'dpi': 300,
  'bbox': [0.5152284263959391,
   0.24930232558139534,
   0.9631979695431472,
   0.30420542280803353],
  'visualization_bbox': {'table': [[32.615976900866215,
     3.392677498047334,
     1030.461020211742,
     158.31856777716183]]},
  'nums_of_visualizations': {'table': 1},
  'caption': 'Table 2. Secondary derived variables constructed for visual exploration in HiDE'},
 {'image_id': 4,
  'file_name': '2076_04.png',
  'page': 3,
  'dpi': 300,
  'bbox': [0.036016949152542374,
   0.15536821350570798,
   0.4851694915254237,
   0.42203488017237456],
  'visualization_bbox': {'map': [[17.101423487544537,
     38.256227758007114,
     1053.5842911877394,
     838.5823754789271]]},
  'nums_of_visualizations': {'map': 1},
  'caption': 'Fig. 3. The 32 London boroughs in the study area. With the exception of ’City’ (not part of the election), boroughs vary in area roughly to equalise voting population.'},
 {'image_id': 5,
  'file_name': '2076_05.png',
  'page': 4,
  'dpi': 300,
  'bbox': [0.05456852791878172,
   0.5506976744186046,
   0.510593220338983,
   0.7823255813953488],
  'visualization_bbox': {'bar_chart': [[534.6058823529412,
     365.59058823529415,
     1049.5964705882352,
     713.604705882353],
    [9.069411764705848,
     367.34823529411767,
     524.0600000000001,
     708.3317647058824],
    [532.8482352941177,
     5.272941176470589,
     1051.354117647059,
     340.9835294117647],
    [9.069411764705848,
     5.272941176470589,
     524.0600000000001,
     344.49882352941177]]},
  'nums_of_visualizations': {'bar_chart': 4},
  'caption': 'Fig. 5. Alpha position and vote order for, all candidates (gray); Labour candidates (red); Conservative (blue) and Liberal Democrat (orange). If no name order bias existed, all bars would be about the same length. '},
 {'image_id': 6,
  'file_name': '2076_06.png',
  'page': 4,
  'dpi': 300,
  'bbox': [0.04568527918781726,
   0.05924418249795603,
   0.9593908629441624,
   0.44651162790697674],
  'visualization_bbox': {'small_multiple': [[67.21357850070721,
     11.939886845827441,
     2114.8515325670496,
     1249.0]]},
  'nums_of_visualizations': {'small_multiple': 1},
  'caption': 'Fig. 4. Alpha position within party (vertical position) and voting rank within party for the three main parties in each ward (vertical bars) in each borough (grid squares). If no name order bias existed, dark and light cells would be randomly distributed in the top, middle and bottom thirds of each borough. Actual voting data show that darker cells (indicating a candidate most votes within their party) are more common in the upper third (listed ﬁrst on the ballot paper within their party) and lighter cells (least votes within party) are more common in the lower third (listed third within their on the ballot paper).'},
 {'image_id': 7,
  'file_name': '2076_07.png',
  'page': 5,
  'dpi': 300,
  'bbox': [0.1116751269035533,
   0.7376744186046512,
   0.4086294416243655,
   0.9209302325581395],
  'visualization_bbox': {'table': [[5.886531365313601,
     2.180811808118081,
     688.480627306273,
     591.0]]},
  'nums_of_visualizations': {'table': 1},
  'caption': 'Table 3. OnoMAP ethnicity categories of candidates'},
 {'image_id': 8,
  'file_name': '2076_08.png',
  'page': 5,
  'dpi': 300,
  'bbox': [0.03807106598984772,
   0.054593019707258356,
   0.9406779661016951,
   0.5293023255813953],
  'visualization_bbox': {'heatmap': [[43.4880514705884,
     39.40073529411765,
     2103.583639705883,
     1531.0]],
   'matrix': [[38.500957854406124,
     32.26245210727969,
     2100.3649425287354,
     1522.2011494252872]]},
  'nums_of_visualizations': {'heatmap': 1, 'matrix': 1},
  'caption': 'Fig. 6. Signed chi values for each candidate arranged by party (left to right) and ballot position within party (top to bottom, row by row). The top third represents candidates ordered ﬁrst in their party, then ordered by absolute position on the ballot paper; the middle third represents candidate ordered second within their party etc. If no name order bias existed, purple and green cells would be randomly distributed within the ballotMap.'},
 {'image_id': 9,
  'file_name': '2076_09.png',
  'page': 6,
  'dpi': 300,
  'bbox': [0.06779661016949153,
   0.054593019707258356,
   0.9593908629441624,
   0.43255813953488376],
  'visualization_bbox': {'heatmap': [[22.659064490464914,
     36.89399114846099,
     495.50959829829407,
     429.4900765577137],
    [505.817615658363,
     30.36654804270463,
     2056.680604982206,
     418.62455516014234],
    [22.121886120996464,
     429.46975088967974,
     464.605871886121,
     822.0658362989324],
    [477.6201067615659,
     422.9626334519573,
     2052.3425266903914,
     813.3896797153025],
    [22.121886120996464,
     824.2348754448399,
     464.605871886121,
     1205.9857651245552],
    [466.7749110320285,
     819.896797153025,
     2052.3425266903914,
     1208.1548042704626]],
   'matrix': [[504.37884872824645,
     31.00535475234271,
     2054.6465863453823,
     417.75635876840704],
    [26.243641231593074,
     37.53279785809907,
     492.9558232931728,
     429.17938420348065],
    [24.61178045515402,
     427.5475234270416,
     463.5823293172692,
     819.1941097724232],
    [476.6372155287819,
     422.6519410977243,
     2051.382864792504,
     812.6666666666669],
    [466.84605087014734,
     817.5622489959841,
     2051.382864792504,
     1207.5769745649266],
    [24.61178045515402,
     824.0896921017404,
     465.21419009370834,
     1207.5769745649266]]},
  'nums_of_visualizations': {'heatmap': 6, 'matrix': 6},
  'caption': 'Fig. 7. Signed chi values for candidates arranged by binary classiﬁcation of name origin and ballot position within party (top to bottom, row by row). The top third represents candidates ordered ﬁrst in their party, then ordered by absolute position on the ballot paper; the middle third represents candidate ordered second within their party etc. Name order bias (tendency for green cells in the upper third and purple in the lower third) is stronger for ‘English or Celtic’ names than for other names where candidates listed ﬁrst are not so likely to get more votes than expected.'},
 {'image_id': 10,
  'file_name': '2076_10.png',
  'page': 7,
  'dpi': 300,
  'bbox': [0.05084745762711865,
   0.054593019707258356,
   0.9322033898305084,
   0.4306976744186046],
  'visualization_bbox': {'heatmap': [[20.966593282395877,
     19.865477949273952,
     2075.9311991751383,
     1213.0],
    [24.357279693486475, 27.885057471264368, 2078.9623161764707, 1213.0]],
   'matrix': [[20.875919117647157,
     28.987132352941178,
     2082.0,
     1206.310661764706]]},
  'nums_of_visualizations': {'heatmap': 2, 'matrix': 1},
  'caption': 'Fig. 8. Signed chi values for each candidate in each borough arranged by binary classiﬁcation of name origin (‘other name origins’ left, ‘English or Celtic’ right) and ballot position within party (top to bottom). The degree of name order bias is indicated by the strength of separation of green (more votes than expected) and purple (fewer votes than expected) cells. This varies by borough and by ethnic origin of candidate names.'}]

In [23]:
pip install pillow

Requirement already satisfied: pillow in ./envs/visimages_processing/lib/python3.13/site-packages (11.2.1)
Note: you may need to restart the kernel to use updated packages.

In [24]:
from PIL import Image

In [25]:
row

missing_image                                            img-09136
figure_id                                                     9135
url              https://data.cyverse.org/dav-anon/iplant/home/...
stem                                                   2076_9000_8
Name: 11, dtype: object

In [26]:
# potentially duplicative

In [27]:
# go through the visualization bbox_ values 
results = []
for i,row in failed.iterrows():
    im_url = row.url
    parts = Path(im_url).stem.split("_")
    # print(row.url)
    #print(list(Path(f"./images/{parts[0]}/{").iterdir()))
    annot_data = annot[parts[0]]
    # visualizations count for this iamge
    
    for e in annot_data:
        vis_count =0
        im_id = e["image_id"]
        for chart,bboxes in e["visualization_bbox"].items():
            for bbox in bboxes:
                p = Path(f"./images/{parts[0]}/{im_id}.png")
                if p.exists():
                    
                    im = Image.open(f"./images/{parts[0]}/{im_id}.png")
                    subfigure = im.crop(bbox)
                    results.append([parts[0],im_id,vis_count,chart,subfigure])
                    vis_count+=1
                else:
                    print("problem",im_id,parts)

problem 7 ['2076', '7000', '0']
problem 7 ['2076', '8000', '0']
problem 7 ['2076', '8000', '1']
problem 7 ['2076', '9000', '0']
problem 7 ['2076', '9000', '1']
problem 7 ['2076', '9000', '2']
problem 7 ['2076', '9000', '3']
problem 7 ['2076', '9000', '4']
problem 7 ['2076', '9000', '5']
problem 7 ['2076', '9000', '6']
problem 7 ['2076', '9000', '7']
problem 7 ['2076', '9000', '8']
problem 7 ['2076', '9000', '9']
problem 7 ['2076', '9000', '10']
problem 7 ['2076', '9000', '11']
problem 7 ['2076', '1000', '1']
problem 7 ['2076', '1000', '2']
problem 8 ['2557', '8000', '0']
problem 8 ['2557', '8000', '0']
problem 8 ['2557', '8000', '0']
problem 8 ['2557', '8000', '1']
problem 8 ['2557', '8000', '1']
problem 8 ['2557', '8000', '1']
problem 8 ['2557', '8000', '2']
problem 8 ['2557', '8000', '2']
problem 8 ['2557', '8000', '2']
problem 8 ['2557', '9000', '0']
problem 8 ['2557', '9000', '0']
problem 8 ['2557', '9000', '0']
problem 8 ['2557', '9000', '1']
problem 8 ['2557', '9000', '1']
problem 8 ['2557', '9000', '1']

In [28]:
len(results)

28436

In [30]:
uniques = []
mapping = set()
for e in results:
    if f"missing_subs/{e[0]}_{e[1]}_{e[2]}_{e[3]}.png" not in mapping:
        mapping.add(f"missing_subs/{e[0]}_{e[1]}_{e[2]}_{e[3]}.png")
        uniques.append(e)

In [31]:
len(uniques)

1705

In [ ]:
len(results)

In [ ]:
for i,e in enumerate(uniques):
    if not Path(f"missing_subs/{e[0]}_{e[1]}_{e[2]}_{e[3]}.png").exists():
        # make sure the image height and width is non zero
        im = e[-1]
        if im.height >0 and im.width > 0:
            im.save(f"missing_subs/{e[0]}_{e[1]}_{e[2]}_{e[3]}.png")

In [ ]:
uniques[46]

In [ ]:
annot["2374"][7]

In [ ]:
Image.open(f"./images/2374/7.png")

In [ ]:
print(i)

In [ ]:
ls missing_subs/ -l | wc -l

In [ ]:
parts[10]

In [ ]:
ls images/2076

In [ ]:
f"{5:<03d}"

In [ ]:
import shutil as sh

In [ ]:
for e in uniques:
    p = Path(f"missing_subs/{e[0]}_{e[1]}_{e[2]}_{e[3]}.png")
    p_out = Path(f"subfigures/{e[0]}_{e[1]:<04d}_{e[2]}.png")
    if p.exists():
        sh.copy(p,p_out)
    # if not p_out.exists():
    #     p_out.symlink_to(p.absolute())

In [33]:
existing_cyverse_images = [e.strip() for e in Path("existing_cyverse_images.txt").read_text().split("\n")[1:]]

In [34]:
existing_cyverse_images[:5]

['1021_0000_0.png',
 '1021_2000_0.png',
 '1021_3000_0.png',
 '1021_3000_1.png',
 '1021_3000_2.png']

In [35]:
len(existing_cyverse_images)

34297

In [36]:
ls subfigures/ -l | wc -l

35852

In [37]:
35853- 34297

1556

In [38]:
after_upload = [e.strip() for e in Path("./contents_after_upload.txt").read_text().split("\n")[1:]]

In [39]:

len(after_upload)

35853

In [40]:
after_upload[:10]

['1021_0000_0.png',
 '1021_2000_0.png',
 '1021_3000_0.png',
 '1021_3000_1.png',
 '1021_3000_2.png',
 '1021_5000_0.png',
 '1021_5000_1.png',
 '1021_5000_2.png',
 '1021_6000_0.png',
 '1021_7000_0.png']

In [41]:
# giong back in and retrieving images that failed the zip extraction
import zipfile as zf

In [42]:
minio_missing = list(Path("images/").glob("*/*minio*"))

In [43]:
minio_missing

[PosixPath('images/2581/8.png.part.minio'),
 PosixPath('images/2076/7.png.part.minio'),
 PosixPath('images/2778/2.png.part.minio'),
 PosixPath('images/373/8.png.part.minio'),
 PosixPath('images/2702/8.png.part.minio'),
 PosixPath('images/2557/8.png.part.minio'),
 PosixPath('images/2606/10.png.part.minio')]

In [44]:
original_paths = [Path(f"{e.parent}/{e.stem.split('.')[0]}.png") for e in minio_missing]

In [45]:
original_paths

[PosixPath('images/2581/8.png'),
 PosixPath('images/2076/7.png'),
 PosixPath('images/2778/2.png'),
 PosixPath('images/373/8.png'),
 PosixPath('images/2702/8.png'),
 PosixPath('images/2557/8.png'),
 PosixPath('images/2606/10.png')]

In [46]:
with zf.ZipFile("./images(1).zip","r") as f:
    # im = f.open(f"{original_paths[0]}").read()
    im = f.open("images/1021/7.png").read()
    print([e for e in f.namelist() if "2581" in e])

['images/2581/', 'images/2581/0.png', 'images/2581/1.png', 'images/2581/2.png', 'images/2581/3.png', 'images/2581/4.png', 'images/2581/5.png', 'images/2581/6.png', 'images/2581/7.png', 'images/2581/8.png.part.minio', 'images/2581/9.png']

In [47]:
missing_images =[f"{Path(e).stem}.png" for e in list(failed.url)]

In [50]:
result = [True in [fail in upload for upload in  after_upload] for fail in missing_images]

In [48]:
probably_minio = []
for fail in missing_images:
    found = False
    for upload in after_upload:
        if fail in upload:
            found = True
            break
    if not found:
        probably_minio.append(fail)

In [49]:
len(probably_minio)

5

In [51]:
found = failed[result]

In [52]:
found

,missing_image,figure_id,url,stem
1,img-09126,9125,https://data.cyverse.org/dav-anon/iplant/home/...,2076_8000_0
2,img-09127,9126,https://data.cyverse.org/dav-anon/iplant/home/...,2076_8000_1
3,img-09128,9127,https://data.cyverse.org/dav-anon/iplant/home/...,2076_9000_0
4,img-09129,9128,https://data.cyverse.org/dav-anon/iplant/home/...,2076_9000_1
5,img-09130,9129,https://data.cyverse.org/dav-anon/iplant/home/...,2076_9000_2
...,...,...,...,...
1575,img-35020,35019,https://data.cyverse.org/dav-anon/iplant/home/...,937_0000_0
1576,img-35021,35020,https://data.cyverse.org/dav-anon/iplant/home/...,937_1000_0
1577,img-35022,35021,https://data.cyverse.org/dav-anon/iplant/home/...,937_2000_0
1578,img-35023,35022,https://data.cyverse.org/dav-anon/iplant/home/...,937_4000_0
1579,img-35024,35023,https://data.cyverse.org/dav-anon/iplant/home/...,937_5000_0

In [53]:
not_found = list(failed[[not e for e in result]].url)

In [54]:
not_found

['https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2076_7000_0.png',
 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2374_7000_2.png',
 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2557_8000_0.png',
 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2557_8000_1.png',
 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2557_8000_2.png']

In [55]:
# need to remove these from the figures table

In [56]:
# then will export to parquet

In [57]:
import duckdb as db

In [58]:
con = db.connect("./visimages.db")

In [59]:
con.sql("SELECT * FROM figure").df()

,paper_id,server_path,caption,chart_type
0,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 2: u, w space diagram",line_chart
1,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 1: World space and image space,line_chart
2,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 3: Metric in (u, w) space",line_chart
3,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 3: Metric in (u, w) space",line_chart
4,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 3: Metric in (u, w) space",line_chart
...,...,...,...,...
35019,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 3. All paths between a set of pages.,graph
35020,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 1. Funnel chart showing dropout rates.,table
35021,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 2. Paths between source/target pairs.,graph
35022,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 5. Difference in flow among groups.,bar_chart
35023,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 4. Inter-site chart showing differences.,graph

In [60]:
prev_figure_database = con.sql("SELECT * FROM figure").df()

In [61]:
removing_minio = prev_figure_database.copy()

In [62]:
not_found

['https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2076_7000_0.png',
 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2374_7000_2.png',
 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2557_8000_0.png',
 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2557_8000_1.png',
 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2557_8000_2.png']

In [68]:
missing_rows = removing_minio[removing_minio.server_path.isin(not_found)]

In [71]:
missing_rows

,paper_id,server_path,caption,chart_type
9124,2098839872,https://data.cyverse.org/dav-anon/iplant/home/...,Table 3. OnoMAP ethnicity categories of candid...,table
14502,2046305401,https://data.cyverse.org/dav-anon/iplant/home/...,Fig. 8. A dual-scale scatterplot comparing the...,scatterplot
18050,2025806111,https://data.cyverse.org/dav-anon/iplant/home/...,Fig. 9. To ﬁnd out whether similarities in the...,bar_chart
18051,2025806111,https://data.cyverse.org/dav-anon/iplant/home/...,Fig. 9. To ﬁnd out whether similarities in the...,bar_chart
18052,2025806111,https://data.cyverse.org/dav-anon/iplant/home/...,Fig. 9. To ﬁnd out whether similarities in the...,box_plot

In [73]:
removing_minio["prev_index"] = removing_minio.index

In [74]:
removing_minio.drop(missing_rows.index)

,paper_id,server_path,caption,chart_type,prev_index
0,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 2: u, w space diagram",line_chart,0
1,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 1: World space and image space,line_chart,1
2,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 3: Metric in (u, w) space",line_chart,2
3,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 3: Metric in (u, w) space",line_chart,3
4,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 3: Metric in (u, w) space",line_chart,4
...,...,...,...,...,...
35019,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 3. All paths between a set of pages.,graph,35019
35020,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 1. Funnel chart showing dropout rates.,table,35020
35021,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 2. Paths between source/target pairs.,graph,35021
35022,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 5. Difference in flow among groups.,bar_chart,35022
35023,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 4. Inter-site chart showing differences.,graph,35023

In [83]:
removing_minio = removing_minio.drop(missing_rows.index).reset_index(drop=True)

In [84]:
removing_minio.to_csv("corrupted_images_removed.csv")

In [81]:
failed.url

0       https://data.cyverse.org/dav-anon/iplant/home/...
1       https://data.cyverse.org/dav-anon/iplant/home/...
2       https://data.cyverse.org/dav-anon/iplant/home/...
3       https://data.cyverse.org/dav-anon/iplant/home/...
4       https://data.cyverse.org/dav-anon/iplant/home/...
                              ...
1575    https://data.cyverse.org/dav-anon/iplant/home/...
1576    https://data.cyverse.org/dav-anon/iplant/home/...
1577    https://data.cyverse.org/dav-anon/iplant/home/...
1578    https://data.cyverse.org/dav-anon/iplant/home/...
1579    https://data.cyverse.org/dav-anon/iplant/home/...
Name: url, Length: 1580, dtype: object

In [87]:
# this is filtering the failed urls from the removing_minio data, so this should be all the new uploaded images that he hasn't downloaded yet

In [86]:
removing_minio[removing_minio.server_path.isin(failed.url)].to_csv("images_zhiyang_might_still_need.csv")

In [93]:
removing_minio

,paper_id,server_path,caption,chart_type,prev_index
0,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 2: u, w space diagram",line_chart,0
1,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 1: World space and image space,line_chart,1
2,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 3: Metric in (u, w) space",line_chart,2
3,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 3: Metric in (u, w) space",line_chart,3
4,2165915693,https://data.cyverse.org/dav-anon/iplant/home/...,"Figure 3: Metric in (u, w) space",line_chart,4
...,...,...,...,...,...
35014,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 3. All paths between a set of pages.,graph,35019
35015,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 1. Funnel chart showing dropout rates.,table,35020
35016,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 2. Paths between source/target pairs.,graph,35021
35017,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 5. Difference in flow among groups.,bar_chart,35022
35018,2162624759,https://data.cyverse.org/dav-anon/iplant/home/...,Figure 4. Inter-site chart showing differences.,graph,35023

In [94]:
removing_minio=removing_minio.drop(["prev_index"],axis=1)

In [95]:
con.sql("DROP TABLE figure")

In [97]:
con.sql("CREATE TABLE figure AS SELECT * FROM removing_minio")

In [98]:
con.close()

In [40]:
fail = original_paths[0]
f"{fail.parent}_{int(fail.stem):<04d}"

'images/2581_8000'

In [99]:
!rm -rf visimages_parquet/

In [101]:
con=db.connect("visimages.db")

In [102]:
con.execute("EXPORT DATABASE 'visimages_parquet' (FORMAT parquet)")