In [1]:
import pandas as pd
df = pd.read_csv("./metadata.csv",header=None,names=["journal","title","doi","link"])

df

,journal,title,doi,link
0,Vis,Interdisciplinary visualization: lessons learn...,10.0000/00000002,http://dl.acm.org/citation.cfm?id=949606&CFID=...
1,Vis,Surface representations of two- and three-dime...,10.1109/VISUAL.1990.146359,http://dx.doi.org/10.1109/VISUAL.1990.146359
2,Vis,FAST: a multi-processed environment for visual...,10.1109/VISUAL.1990.146360,http://dx.doi.org/10.1109/VISUAL.1990.146360
3,Vis,The VIS-5D system for easy interactive visuali...,10.1109/VISUAL.1990.146361,http://dx.doi.org/10.1109/VISUAL.1990.146361
4,Vis,A procedural interface for volume rendering,10.1109/VISUAL.1990.146362,http://dx.doi.org/10.1109/VISUAL.1990.146362
...,...,...,...,...
3096,VAST,RegressionExplorer: Interactive Exploration of...,10.1109/TVCG.2018.2865043,http://dx.doi.org/10.1109/TVCG.2018.2865043
3097,VAST,Seq2Seq-Vis: A Visual Debugging Tool for Seque...,10.1109/TVCG.2018.2865044,http://dx.doi.org/10.1109/TVCG.2018.2865044
3098,VAST,"SIRIUS: Dual, Symmetric, Interactive Dimension...",10.1109/TVCG.2018.2865047,http://dx.doi.org/10.1109/TVCG.2018.2865047
3099,VAST,MotionRugs: Visualizing Collective Trends in S...,10.1109/TVCG.2018.2865049,http://dx.doi.org/10.1109/TVCG.2018.2865049
3100,VAST,Drag and Track: A Direct Manipulation Interfac...,10.1109/TVCG.2018.2865051,http://dx.doi.org/10.1109/TVCG.2018.2865051

In [2]:
dois = df[df.link.str.contains("doi.org")]

In [3]:
dois

,journal,title,doi,link
1,Vis,Surface representations of two- and three-dime...,10.1109/VISUAL.1990.146359,http://dx.doi.org/10.1109/VISUAL.1990.146359
2,Vis,FAST: a multi-processed environment for visual...,10.1109/VISUAL.1990.146360,http://dx.doi.org/10.1109/VISUAL.1990.146360
3,Vis,The VIS-5D system for easy interactive visuali...,10.1109/VISUAL.1990.146361,http://dx.doi.org/10.1109/VISUAL.1990.146361
4,Vis,A procedural interface for volume rendering,10.1109/VISUAL.1990.146362,http://dx.doi.org/10.1109/VISUAL.1990.146362
5,Vis,Techniques for the interactive visualization o...,10.1109/VISUAL.1990.146363,http://dx.doi.org/10.1109/VISUAL.1990.146363
...,...,...,...,...
3096,VAST,RegressionExplorer: Interactive Exploration of...,10.1109/TVCG.2018.2865043,http://dx.doi.org/10.1109/TVCG.2018.2865043
3097,VAST,Seq2Seq-Vis: A Visual Debugging Tool for Seque...,10.1109/TVCG.2018.2865044,http://dx.doi.org/10.1109/TVCG.2018.2865044
3098,VAST,"SIRIUS: Dual, Symmetric, Interactive Dimension...",10.1109/TVCG.2018.2865047,http://dx.doi.org/10.1109/TVCG.2018.2865047
3099,VAST,MotionRugs: Visualizing Collective Trends in S...,10.1109/TVCG.2018.2865049,http://dx.doi.org/10.1109/TVCG.2018.2865049
3100,VAST,Drag and Track: A Direct Manipulation Interfac...,10.1109/TVCG.2018.2865051,http://dx.doi.org/10.1109/TVCG.2018.2865051

In [4]:
# %load ../../vis-sieve/openalex_code/database/create_database.py
import duckdb as db

def create(name):
    # TODO add in code to handle if the .db isn't added
    con = db.connect(f'{name}')
    con.execute('''
                DROP TABLE IF EXISTS residence;
                DROP TABLE IF EXISTS contribution;
                DROP TABLE IF EXISTS figure_property;
                DROP TABLE IF EXISTS figure;
                DROP TABLE IF EXISTS author;
                DROP TABLE IF EXISTS institution;
                DROP TABLE IF EXISTS paper;
                ''')


    con.execute('''
    CREATE TABLE author (
        id BIGINT,
        name VARCHAR(100) NOT NULL
    );
                
    CREATE TABLE institution (
        id BIGINT ,
        ror VARCHAR(20) NOT NULL,
        name VARCHAR(100) NOT NULL
    );
                
    CREATE TABLE residence (
        au_id BIGINT,
        inst_id BIGINT,
    );
                
    CREATE TABLE paper (
        id BIGINT ,
        title VARCHAR(200) NOT NULL,
        doi VARCHAR(100),
        publication_date DATE,
        oa_url VARCHAR(200),
        pdf_path VARCHAR(150),
        inst_id BIGINT,
    );
                
    CREATE TABLE contribution (
        au_id BIGINT,
        paper_id BIGINT,
    );
                
    CREATE TABLE figure (
        id BIGINT ,
        paper_id BIGINT,
        local_path VARCHAR(150),
        server_path VARCHAR(150),
    );
                
    CREATE TABLE figure_property (
        name VARCHAR(100),
        int_value INTEGER,
        string_value VARCHAR(100),
        figure_id BIGINT,
    );
                

    ''')

    con.close()

In [20]:
# %load ../../vis-sieve/openalex_code/hear_me_ROR_script.py
"""
file: hear_me_ROR_script.py
author: Ben Kruse
Adapted from: hear_me_ROR.ipynb by Devin Bayly

Takes a ROR identification of school and a range of years,
then generates a json file with the publications of the school
for that period
"""

# from database.create_database import create
from pathlib import Path
import os
import requests as rq
import json
import argparse
from tqdm import tqdm
import math
import duckdb as db

def remove_duplicate_authors(publications, silent=False):
    """ Removes duplicate authors from a list of publications

    Args:
        publications (list): list of publications to remove duplicate authors from

    Returns:
        list: list of publications with duplicate authors removed
    """
    for pub in publications:
        authors = pub["authorships"]
        seen_ids = set()
        new_authors = []
        for a in authors:
            if a["author"]["id"] not in seen_ids:
                new_authors.append(a)
                seen_ids.add(a["author"]["id"])
            else: 
                print(f"Duplicate author in {pub['title']}: {a['author']['display_name']}")
        pub["authorships"] = new_authors
    return publications

def results_per_year(year, ror="03m2x1q45", silent=False, filter_duplicate_authors=True, testing=False):
    """ Gets the publications for a school for a year

    Args:
        year (int): year to get publications for
        ror (str): ROR identification of the school

    Returns:
        list: list of publications for the school for the year
    """
    all_res = []
    headers = {"mailto":"baylyd@arizona.edu"} ## Make command line arg
    res = rq.get(f"https://api.openalex.org/works?filter=publication_year:{year},institutions.ror:{ror}&cursor=*&per-page=200",headers=headers)
    data = res.json()
    if filter_duplicate_authors:
        data["results"] = remove_duplicate_authors(data["results"], silent=silent)
    page_count = data["meta"]["count"]/data["meta"]["per_page"]
    all_res.extend(data["results"])
    cursor = data["meta"]["next_cursor"]
    query = 0
    if not silent:
        pbar = tqdm(total=math.ceil(page_count))
    while cursor:
        query+=1
        res = rq.get(f"https://api.openalex.org/works?filter=publication_year:{year},institutions.ror:{ror}&cursor={cursor}&per-page=200")
        
        # Sometimes request fails, leave the year (find better way)
        try:
            data = res.json()
        except json.decoder.JSONDecodeError:
            print(f"Error on query {query}")
            print(res.text)
            break

        if filter_duplicate_authors:
            data["results"] = remove_duplicate_authors(data["results"], silent=silent)
        all_res.extend(data["results"])
        cursor = data["meta"].get("next_cursor",None)
        if not silent:
            pbar.update(1)
        if testing:
            break
    return all_res
def doi_result(doi_url,testing=False):
    """ Gets the publications for a school for a year

    Args:
        year (int): year to get publications for
        ror (str): ROR identification of the school

    Returns:
        list: list of publications for the school for the year
    """
    all_res = []
    headers = {"mailto":"baylyd@arizona.edu"} ## Make command line arg
    res = rq.get(f"https://api.openalex.org/works/{doi_url}",headers=headers)
    data = res.json()
    if testing:
        print(data)
    
    return data

def get_publications(ror: str, years: range, output_file: str, silent=False, get_authors=False):
    """ Gets the publications for a school for a range of years and 
    writes them to a json file

    Args:
        ror (str): ROR identification of the school
        years (range): range of years to get publications for
    
    Returns:
        None
    """
    all_res = []
    for year in years:
        if not silent:
            print(f"Getting publications for {year}")
        all_res.extend(results_per_year(year, ror, silent))
    with open(output_file,"w") as f:
        json.dump(all_res,f)

    if get_authors:
        if not silent:
            print("Getting authors")
        with open("authors"+output_file,"w") as f:
            json.dump(get_all_authors(all_res, output_file), f)
        

def get_all_authors(publications, output_file):
    """ Gets the authors from a list of publications

    Args:
        publications (list): list of publications to get authors from

    Returns:
        list: list of authors from the publications
    """
    authors = {}
    author_ids = {}
    for pub in publications:
        for a in pub["authorships"]:
            publication = {"work_id": pub["id"], 
                           "author": {"id": a["author"]["id"], 
                                      "display_name": a["author"]["display_name"], 
                                      "orcid": a["author"]["orcid"]
                                      },
                            "open_access": pub["open_access"]
                            }
            if a["author"]["id"] not in author_ids:
                pub_array = [publication]
                author_ids[a["author"]["id"]] = pub_array
                authors[a["author"]["display_name"]] = pub_array
            else:
                author_ids[a["author"]["id"]].append(publication)

    return authors


def add_institution_to_db(con: db.DuckDBPyConnection, institution_ror: str = None, 
                          institution_name: str = None, institution_id: int = None) -> int:
    """ Adds an institution to the database

    Args:
        con (db.DuckDBPyConnection): connection to the database
        institution_ror (str): ROR identification of the institution

    Returns:
        int: id of the institution
    """

    if institution_ror is not None:
        institution_info = rq.get(f"https://api.openalex.org/institutions/https://ror.org/{institution_ror}").json()
        institution_name = institution_name or institution_info["display_name"]
        institution_id = institution_id or int(institution_info["id"].split("I")[-1])

    elif institution_id is not None:
        con.execute(f"SELECT COUNT(1) FROM institution WHERE id = {institution_id};")
        exists = con.fetchone()[0]
        if exists:
            pass
            return institution_id
        
        institution_info = rq.get(f"https://api.openalex.org/institutions/I{institution_id}").json()
        institution_name = institution_name or institution_info["display_name"]
        institution_ror = institution_ror or institution_info["ror"].split("/")[-1]
        
    institution_name = institution_name.replace("'", "")
    try:
        con.execute(f"INSERT INTO institution VALUES ({institution_id}, '{institution_ror}', '{institution_name}');")
    except db.ConstraintException:
        pass

    return institution_id
    
def populate_database(database_file: str, ror: str, years: range, content_root: str,
                      json_output: str = None, silent: bool = False,dois=None) -> None:
    """ Populates a database with publications for a school for a range of years

    Args:
        database_file (str): name of the database file to populate
        ror (str): ROR identification of the school
        years (range): range of years to get publications for
        json_output (str): name of the json file to write the publications to
        silent (bool): silence output
    """
    con = db.connect(database_file)
    inst_id = add_institution_to_db(con, institution_ror=ror)
    failed_rows =[]
    all_results =[]
    if type(dois) !=type(None):
        # iterate over the dois, and make a similar function as results_per_year but to retrieve a single result provided a doi string
        for index,row in tqdm(dois.iterrows()):
            
            link = row.link
            pub = doi_result(link)
            # double check that we are getting a dictionary back not a list of results
            
            if type(pub) == type(dict()):
                all_results.append(pub)
                # this is a list of probably one element or more if multiple matched the doi
            
            
                # Add publication to database
                #await add_publication_and_figures(con, pub, content_root, playwright)
                # TODO wrap these publication table lines in a function
                
                pub_date = pub["publication_date"]
                pub_id = int(pub["id"].split("W")[-1])
                title = pub["title"]
                if not title:
                  print("title is none ",pub)
                  continue
                pub_title = title[:200].replace("'", "")
                pub_doi = pub["doi"]
                pub_oa_url = pub["open_access"]["oa_url"]
                pub_inst_id = inst_id
                pub_oa_status = pub["open_access"]["oa_status"]
                # # this section is checking for whether the table has the paper in it already
                # con.execute(f"SELECT COUNT(1) FROM paper WHERE id = {pub_id};")
                # exists = con.fetchone()[0]
                
                # if exists:
                #     # want to continue to the next publication and not try to update either paper table, or the authorship tables, because this has already happened
                #     continue
    
                con.execute(f"""INSERT INTO paper (id, title, doi, publication_date, oa_url,inst_id) VALUES ({pub_id}, '{pub_title}', '{pub_doi}', '{pub_date}', '{pub_oa_url}','{pub_inst_id}');""")
                for a in pub["authorships"]:
                    # TODO make sure filter the authors and only include the people that are actually affiliated with our ROR code 
                    institutions = a["institutions"]
                    # get the rors from the institutions author is affiliated with
                    # use path to trim off only the last part
                    rors = [Path(i["ror"]).stem for i in institutions]
                    # only add the author to the table if we see their affiliation with the university 
                    try:
                        con.execute(f"""INSERT INTO author VALUES ({a['author']['id'].split('A')[-1]}, '{a['author']['display_name'].replace("'", "")}');""")
                    except db.ConstraintException:
                        pass

                    try:
                        con.execute(f"INSERT INTO contribution VALUES ({a['author']['id'].split('A')[-1]}, {pub['id'].split('W')[-1]});")
                    except db.ConstraintException:
                        pass
                    
                    for author_inst in a["institutions"]:
                        # Making another change from Ben's code
                        add_institution_to_db(con, institution_id=int(author_inst["id"].split("I")[-1]))
                        try:
                            con.execute(f"INSERT INTO residence VALUES ({a['author']['id'].split('A')[-1]}, {author_inst['id'].split('I')[-1]});")
                        except db.ConstraintException:
                            pass
            else:
                failed_rows.append(row)
    Path(json_output).write_text(json.dumps(all_results))
    return failed_rows,all_results

In [5]:
from pathlib import Path

In [25]:
# recreating setup
db_file = Path("visimages.db")
create(db_file)
fails,successes = populate_database(db_file, "03m2x1q45", range(2000,2025),"./openalex_visimages", "Hear_me_ROR_out_visimages.json", True,dois)
# get all authors

3053it [20:00,  2.54it/s]

In [26]:
len(successes)

3053

In [21]:
all_authors = get_all_authors(successes,"./Hear_me_ROR_out_visimages.json")

In [5]:
import duckdb as db

In [6]:
con = db.connect("visimages.db")

In [7]:
con.sql("SHOW TABLES").show()

┌─────────────────┐
│      name       │
│     varchar     │
├─────────────────┤
│ author          │
│ contribution    │
│ figure          │
│ figure_property │
│ institution     │
│ paper           │
│ residence       │
└─────────────────┘

In [8]:
con.sql("SELECT * FROM PAPER")

┌────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────┬──────────────────┬───────────────────────────────────────────────────────────────────────────────────────┬──────────┬───────────┐
│     id     │                                                         title                                                          │                    doi                     │ publication_date │                                        oa_url                                         │ pdf_path │  inst_id  │
│   int64    │                                                        varchar                                                         │                  varchar                   │       date       │                                        varchar                                        │ varchar  │   int64   │
├────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼──────────────────┼───────────────────────────────────────────────────────────────────────────────────────┼──────────┼───────────┤
│ 3085563693 │ Surface representations of two- and three-dimensional fluid flow topology                                              │ https://doi.org/10.1109/visual.1990.146359 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 3041520455 │ FAST: a multi-processed environment for visualization of computational fluid dynamics                                  │ https://doi.org/10.1109/visual.1990.146360 │ 2002-12-04       │ https://jaxa.repo.nii.ac.jp/record/43435/files/nalsp0014002.pdf                       │ NULL     │ 138006243 │
│ 4237685258 │ The VIS-5D system for easy interactive visualization                                                                   │ https://doi.org/10.1109/visual.1990.146361 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4241306103 │ A procedural interface for volume rendering                                                                            │ https://doi.org/10.1109/visual.1990.146362 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4242274056 │ Techniques for the interactive visualization of volumetric data                                                        │ https://doi.org/10.1109/visual.1990.146363 │ 2002-12-04       │ https://escholarship.org/content/qt4367m3t4/qt4367m3t4.pdf?t=ptt2h6                   │ NULL     │ 138006243 │
│ 4235544651 │ Displaying voxel-based objects according to their qualitative shape synthesis                                          │ https://doi.org/10.1109/visual.1990.146364 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4243289651 │ Interpreting a 3D object from a rough 2D line drawing                                                                  │ https://doi.org/10.1109/visual.1990.146365 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4232108933 │ Animation techniques for chain-coded objects                                                                           │ https://doi.org/10.1109/visual.1990.146366 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4239445310 │ Extracting geometric models through constraint minimization                                                            │ https://doi.org/10.1109/visual.1990.146367 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4252612379 │ Wide-band relativistic Doppler effect visualization                                                                    │ https://doi.org/10.1109/visual.1990.146368 │ 2002-12-04       │ http://www.ri.cmu.edu/pub_files/pub2/hsiung_p_k_1990_1/hsiung_p_k_1990_1.pdf          │ NULL     │ 138006243 │
│      ·     │                          ·                                                                                             │                     ·                      │     ·            │                     ·                                                                 │  ·       │     ·     │
│      ·     │                          ·                                                                                             │                     ·                      │     ·            │                     ·                                                                 │  ·       │     ·     │
│      ·     │                          ·                                                                                             │                     ·                      │     ·            │                     ·                                                                 │  ·       │     ·     │
│ 2894279555 │ Situ: Identifying and Explaining Suspicious Behavior in Networks                                                       │ https://doi.org/10.1109/tvcg.2018.2865029  │ 2018-08-20       │ https://www.osti.gov/servlets/purl/1486963                                            │ NULL     │ 138006243 │
│ 2896091756 │ Enhancing Web-based Analytics Applications through Provenance                                                          │ https://doi.org/10.1109/tvcg.2018.2865039  │ 2018-10-19       │ None                                                                                  │ NULL     │ 138006243 │
│ 2904955348 │ Futzing and Moseying: Interviews with Professional Data Analysts on Exploration Practices                              │ https://doi.org/10.1109/tvcg.2018.2865040  │ 2018-08-20       │ https://escholarship.org/content/qt04g0z5gn/qt04g0z5gn.pdf?t=pvt8ml                   │ NULL     │ 138006243 │
│ 2888032845 │ ForVizor: Visualizing Spatio-Temporal Team Formations in Soccer                                                        │ https://doi.org/10.1109/tvcg.2018.2865041  │ 2018-08-20       │ None                                                                                  │ NULL     │ 138006243 │
│ 2890529371 │ Identification of Temporally Varying Areas of Interest in Long-Duration Eye-Tracking Data Sets                         │ https://doi.org/10.1109/tvcg.2018.2865042  │ 2018-09-03       │ None                                                                                  │ NULL     │ 138006243 │
│ 2889730816 │ RegressionExplorer: Interactive Exploration of Logistic Regression Models with Subgroup Analysis                       │ https://doi.org/10.1109/tvcg.2018.2865043  │ 2018-09-13       │ https://pure.tue.nl/ws/files/116894719/08464305.pdf                                   │ NULL     │ 138006243 │
│ 2963123635 │ Seq2seq-Vis: A Visual Debugging Tool for Sequence-to-Sequence Models                                                   │ https://doi.org/10.1109/tvcg.2018.2865044  │ 2018-10-17       │ https://arxiv.org/pdf/1804.09299                                                      │ NULL     │ 138006243 │
│ 2888244365 │ SIRIUS: Dual, Symmetric, Interactive Dimension Reductions                                                              │ https://doi.org/10.1109/tvcg.2018.2865047  │ 2018-08-20       │ None                                                                                  │ NULL     │ 138006243 │
│ 2888207115 │ MotionRugs: Visualizing Collective Trends in Space and Time                                                            │ https://doi.org/10.1109/tvcg.2018.2865049  │ 2018-08-20       │ https://kops.uni-konstanz.de/bitstreams/6238ff7a-1096-4aae-8144-4c2cd238c198/download │ NULL     │ 138006243 │
│ 2886794935 │ Drag and Track: A Direct Manipulation Interface for Contextualizing Data Instances within a Continuous Parameter Space │ https://doi.org/10.1109/tvcg.2018.2865051  │ 2018-08-20       │ None                                                                                  │ NULL     │ 138006243 │
├────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────┴──────────────────┴───────────────────────────────────────────────────────────────────────────────────────┴──────────┴───────────┤
│ 3053 rows (20 shown)                                                                                                                                                                                                                                                                                     7 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [9]:
type(None) != type(None)

False

In [10]:
[row.link for index,row in dois.iterrows()]

['http://dx.doi.org/10.1109/VISUAL.1990.146359',
 'http://dx.doi.org/10.1109/VISUAL.1990.146360',
 'http://dx.doi.org/10.1109/VISUAL.1990.146361',
 'http://dx.doi.org/10.1109/VISUAL.1990.146362',
 'http://dx.doi.org/10.1109/VISUAL.1990.146363',
 'http://dx.doi.org/10.1109/VISUAL.1990.146364',
 'http://dx.doi.org/10.1109/VISUAL.1990.146365',
 'http://dx.doi.org/10.1109/VISUAL.1990.146366',
 'http://dx.doi.org/10.1109/VISUAL.1990.146367',
 'http://dx.doi.org/10.1109/VISUAL.1990.146368',
 'http://dx.doi.org/10.1109/VISUAL.1990.146369',
 'http://dx.doi.org/10.1109/VISUAL.1990.146370',
 'http://dx.doi.org/10.1109/VISUAL.1990.146371',
 'http://dx.doi.org/10.1109/VISUAL.1990.146372',
 'http://dx.doi.org/10.1109/VISUAL.1990.146373',
 'http://dx.doi.org/10.1109/VISUAL.1990.146374',
 'http://dx.doi.org/10.1109/VISUAL.1990.146375',
 'http://dx.doi.org/10.1109/VISUAL.1990.146376',
 'http://dx.doi.org/10.1109/VISUAL.1990.146377',
 'http://dx.doi.org/10.1109/VISUAL.1990.146378',
 'http://dx.doi.org/10.1109/VISUAL.1990.146379',
 'http://dx.doi.org/10.1109/VISUAL.1990.146380',
 'http://dx.doi.org/10.1109/VISUAL.1990.146381',
 'http://dx.doi.org/10.1109/VISUAL.1990.146382',
 'http://dx.doi.org/10.1109/VISUAL.1990.146383',
 'http://dx.doi.org/10.1109/VISUAL.1990.146384',
 'http://dx.doi.org/10.1109/VISUAL.1990.146385',
 'http://dx.doi.org/10.1109/VISUAL.1990.146386',
 'http://dx.doi.org/10.1109/VISUAL.1990.146387',
 'http://dx.doi.org/10.1109/VISUAL.1990.146388',
 'http://dx.doi.org/10.1109/VISUAL.1990.146389',
 'http://dx.doi.org/10.1109/VISUAL.1990.146390',
 'http://dx.doi.org/10.1109/VISUAL.1990.146391',
 'http://dx.doi.org/10.1109/VISUAL.1990.146392',
 'http://dx.doi.org/10.1109/VISUAL.1990.146393',
 'http://dx.doi.org/10.1109/VISUAL.1990.146394',
 'http://dx.doi.org/10.1109/VISUAL.1990.146395',
 'http://dx.doi.org/10.1109/VISUAL.1990.146396',
 'http://dx.doi.org/10.1109/VISUAL.1990.146397',
 'http://dx.doi.org/10.1109/VISUAL.1990.146398',
 'http://dx.doi.org/10.1109/VISUAL.1990.146399',
 'http://dx.doi.org/10.1109/VISUAL.1990.146400',
 'http://dx.doi.org/10.1109/VISUAL.1990.146401',
 'http://dx.doi.org/10.1109/VISUAL.1990.146402',
 'http://dx.doi.org/10.1109/VISUAL.1990.146403',
 'http://dx.doi.org/10.1109/VISUAL.1990.146412',
 'http://dx.doi.org/10.1109/VISUAL.1990.146413',
 'http://dx.doi.org/10.1109/VISUAL.1990.146414',
 'http://dx.doi.org/10.1109/VISUAL.1990.146415',
 'http://dx.doi.org/10.1109/VISUAL.1990.146416',
 'http://dx.doi.org/10.1109/VISUAL.1990.146417',
 'http://dx.doi.org/10.1109/VISUAL.1990.146418',
 'http://dx.doi.org/10.1109/VISUAL.1990.146419',
 'http://dx.doi.org/10.1109/VISUAL.1991.175767',
 'http://dx.doi.org/10.1109/VISUAL.1991.175770',
 'http://dx.doi.org/10.1109/VISUAL.1991.175771',
 'http://dx.doi.org/10.1109/VISUAL.1991.175772',
 'http://dx.doi.org/10.1109/VISUAL.1991.175773',
 'http://dx.doi.org/10.1109/VISUAL.1991.175776',
 'http://dx.doi.org/10.1109/VISUAL.1991.175777',
 'http://dx.doi.org/10.1109/VISUAL.1991.175778',
 'http://dx.doi.org/10.1109/VISUAL.1991.175780',
 'http://dx.doi.org/10.1109/VISUAL.1991.175781',
 'http://dx.doi.org/10.1109/VISUAL.1991.175782',
 'http://dx.doi.org/10.1109/VISUAL.1991.175784',
 'http://dx.doi.org/10.1109/VISUAL.1991.175785',
 'http://dx.doi.org/10.1109/VISUAL.1991.175786',
 'http://dx.doi.org/10.1109/VISUAL.1991.175787',
 'http://dx.doi.org/10.1109/VISUAL.1991.175789',
 'http://dx.doi.org/10.1109/VISUAL.1991.175790',
 'http://dx.doi.org/10.1109/VISUAL.1991.175791',
 'http://dx.doi.org/10.1109/VISUAL.1991.175792',
 'http://dx.doi.org/10.1109/VISUAL.1991.175794',
 'http://dx.doi.org/10.1109/VISUAL.1991.175795',
 'http://dx.doi.org/10.1109/VISUAL.1991.175796',
 'http://dx.doi.org/10.1109/VISUAL.1991.175797',
 'http://dx.doi.org/10.1109/VISUAL.1991.175799',
 'http://dx.doi.org/10.1109/VISUAL.1991.175800',
 'http://dx.doi.org/10.1109/VISUAL.1991.175801',
 'http://dx.doi.org/10.1109/VISUAL.1991.175802',
 'http://dx.doi.org/10.1109/VISUAL.1991.175804',
 'http://dx.doi.org/10.1109/VISUAL.1991.175805',
 'http://dx.doi.org/10.1109/VISUAL.1991.175806',
 'http://dx.doi.org/10.1109/VISUAL.1991.175807',
 'http://dx.doi.org/10.1109/VISUAL.1991.175809',
 'http://dx.doi.org/10.1109/VISUAL.1991.175810',
 'http://dx.doi.org/10.1109/VISUAL.1991.175811',
 'http://dx.doi.org/10.1109/VISUAL.1991.175812',
 'http://dx.doi.org/10.1109/VISUAL.1991.175814',
 'http://dx.doi.org/10.1109/VISUAL.1991.175815',
 'http://dx.doi.org/10.1109/VISUAL.1991.175816',
 'http://dx.doi.org/10.1109/VISUAL.1991.175818',
 'http://dx.doi.org/10.1109/VISUAL.1991.175819',
 'http://dx.doi.org/10.1109/VISUAL.1991.175820',
 'http://dx.doi.org/10.1109/VISUAL.1991.175821',
 'http://dx.doi.org/10.1109/VISUAL.1991.175823',
 'http://dx.doi.org/10.1109/VISUAL.1991.175824',
 'http://dx.doi.org/10.1109/VISUAL.1991.175825',
 'http://dx.doi.org/10.1109/VISUAL.1991.175826',
 'http://dx.doi.org/10.1109/VISUAL.1991.175827',
 'http://dx.doi.org/10.1109/VISUAL.1991.175828',
 'http://dx.doi.org/10.1109/VISUAL.1991.175830',
 'http://dx.doi.org/10.1109/VISUAL.1991.175831',
 'http://dx.doi.org/10.1109/VISUAL.1991.175832',
 'http://dx.doi.org/10.1109/VISUAL.1991.175833',
 'http://dx.doi.org/10.1109/VISUAL.1991.175834',
 'http://dx.doi.org/10.1109/VISUAL.1991.175835',
 'http://dx.doi.org/10.1109/VISUAL.1991.175836',
 'http://dx.doi.org/10.1109/VISUAL.1991.175837',
 'http://dx.doi.org/10.1109/VISUAL.1991.175838',
 'http://dx.doi.org/10.1109/VISUAL.1992.235173',
 'http://dx.doi.org/10.1109/VISUAL.1992.235174',
 'http://dx.doi.org/10.1109/VISUAL.1992.235175',
 'http://dx.doi.org/10.1109/VISUAL.1992.235176',
 'http://dx.doi.org/10.1109/VISUAL.1992.235177',
 'http://dx.doi.org/10.1109/VISUAL.1992.235178',
 'http://dx.doi.org/10.1109/VISUAL.1992.235179',
 'http://dx.doi.org/10.1109/VISUAL.1992.235180',
 'http://dx.doi.org/10.1109/VISUAL.1992.235181',
 'http://dx.doi.org/10.1109/VISUAL.1992.235182',
 'http://dx.doi.org/10.1109/VISUAL.1992.235183',
 'http://dx.doi.org/10.1109/VISUAL.1992.235184',
 'http://dx.doi.org/10.1109/VISUAL.1992.235185',
 'http://dx.doi.org/10.1109/VISUAL.1992.235186',
 'http://dx.doi.org/10.1109/VISUAL.1992.235187',
 'http://dx.doi.org/10.1109/VISUAL.1992.235188',
 'http://dx.doi.org/10.1109/VISUAL.1992.235189',
 'http://dx.doi.org/10.1109/VISUAL.1992.235190',
 'http://dx.doi.org/10.1109/VISUAL.1992.235191',
 'http://dx.doi.org/10.1109/VISUAL.1992.235192',
 'http://dx.doi.org/10.1109/VISUAL.1992.235193',
 'http://dx.doi.org/10.1109/VISUAL.1992.235194',
 'http://dx.doi.org/10.1109/VISUAL.1992.235195',
 'http://dx.doi.org/10.1109/VISUAL.1992.235196',
 'http://dx.doi.org/10.1109/VISUAL.1992.235197',
 'http://dx.doi.org/10.1109/VISUAL.1992.235198',
 'http://dx.doi.org/10.1109/VISUAL.1992.235199',
 'http://dx.doi.org/10.1109/VISUAL.1992.235200',
 'http://dx.doi.org/10.1109/VISUAL.1992.235201',
 'http://dx.doi.org/10.1109/VISUAL.1992.235202',
 'http://dx.doi.org/10.1109/VISUAL.1992.235203',
 'http://dx.doi.org/10.1109/VISUAL.1992.235204',
 'http://dx.doi.org/10.1109/VISUAL.1992.235205',
 'http://dx.doi.org/10.1109/VISUAL.1992.235206',
 'http://dx.doi.org/10.1109/VISUAL.1992.235207',
 'http://dx.doi.org/10.1109/VISUAL.1992.235208',
 'http://dx.doi.org/10.1109/VISUAL.1992.235209',
 'http://dx.doi.org/10.1109/VISUAL.1992.235210',
 'http://dx.doi.org/10.1109/VISUAL.1992.235211',
 'http://dx.doi.org/10.1109/VISUAL.1992.235212',
 'http://dx.doi.org/10.1109/VISUAL.1992.235213',
 'http://dx.doi.org/10.1109/VISUAL.1992.235214',
 'http://dx.doi.org/10.1109/VISUAL.1992.235215',
 'http://dx.doi.org/10.1109/VISUAL.1992.235216',
 'http://dx.doi.org/10.1109/VISUAL.1992.235217',
 'http://dx.doi.org/10.1109/VISUAL.1992.235218',
 'http://dx.doi.org/10.1109/VISUAL.1992.235219',
 'http://dx.doi.org/10.1109/VISUAL.1992.235220',
 'http://dx.doi.org/10.1109/VISUAL.1992.235221',
 'http://dx.doi.org/10.1109/VISUAL.1992.235222',
 'http://dx.doi.org/10.1109/VISUAL.1992.235223',
 'http://dx.doi.org/10.1109/VISUAL.1992.235224',
 'http://dx.doi.org/10.1109/VISUAL.1992.235225',
 'http://dx.doi.org/10.1109/VISUAL.1992.235226',
 'http://dx.doi.org/10.1109/VISUAL.1992.235227',
 'http://dx.doi.org/10.1109/VISUAL.1992.235228',
 'http://dx.doi.org/10.1109/VISUAL.1992.235229',
 'http://dx.doi.org/10.1109/VISUAL.1992.235230',
 'http://dx.doi.org/10.1109/VISUAL.1992.235231',
 'http://dx.doi.org/10.1109/VISUAL.1993.398845',
 'http://dx.doi.org/10.1109/VISUAL.1993.398846',
 'http://dx.doi.org/10.1109/VISUAL.1993.398847',
 'http://dx.doi.org/10.1109/VISUAL.1993.398848',
 'http://dx.doi.org/10.1109/VISUAL.1993.398849',
 'http://dx.doi.org/10.1109/VISUAL.1993.398850',
 'http://dx.doi.org/10.1109/VISUAL.1993.398851',
 'http://dx.doi.org/10.1109/VISUAL.1993.398852',
 'http://dx.doi.org/10.1109/VISUAL.1993.398853',
 'http://dx.doi.org/10.1109/VISUAL.1993.398854',
 'http://dx.doi.org/10.1109/VISUAL.1993.398855',
 'http://dx.doi.org/10.1109/VISUAL.1993.398856',
 'http://dx.doi.org/10.1109/VISUAL.1993.398857',
 'http://dx.doi.org/10.1109/VISUAL.1993.398858',
 'http://dx.doi.org/10.1109/VISUAL.1993.398859',
 'http://dx.doi.org/10.1109/VISUAL.1993.398860',
 'http://dx.doi.org/10.1109/VISUAL.1993.398861',
 'http://dx.doi.org/10.1109/VISUAL.1993.398862',
 'http://dx.doi.org/10.1109/VISUAL.1993.398863',
 'http://dx.doi.org/10.1109/VISUAL.1993.398864',
 'http://dx.doi.org/10.1109/VISUAL.1993.398865',
 'http://dx.doi.org/10.1109/VISUAL.1993.398866',
 'http://dx.doi.org/10.1109/VISUAL.1993.398867',
 'http://dx.doi.org/10.1109/VISUAL.1993.398868',
 'http://dx.doi.org/10.1109/VISUAL.1993.398869',
 'http://dx.doi.org/10.1109/VISUAL.1993.398870',
 'http://dx.doi.org/10.1109/VISUAL.1993.398871',
 'http://dx.doi.org/10.1109/VISUAL.1993.398872',
 'http://dx.doi.org/10.1109/VISUAL.1993.398873',
 'http://dx.doi.org/10.1109/VISUAL.1993.398874',
 'http://dx.doi.org/10.1109/VISUAL.1993.398875',
 'http://dx.doi.org/10.1109/VISUAL.1993.398876',
 'http://dx.doi.org/10.1109/VISUAL.1993.398877',
 'http://dx.doi.org/10.1109/VISUAL.1993.398878',
 'http://dx.doi.org/10.1109/VISUAL.1993.398879',
 'http://dx.doi.org/10.1109/VISUAL.1993.398880',
 'http://dx.doi.org/10.1109/VISUAL.1993.398881',
 'http://dx.doi.org/10.1109/VISUAL.1993.398882',
 'http://dx.doi.org/10.1109/VISUAL.1993.398883',
 'http://dx.doi.org/10.1109/VISUAL.1993.398884',
 'http://dx.doi.org/10.1109/VISUAL.1993.398885',
 'http://dx.doi.org/10.1109/VISUAL.1993.398892',
 'http://dx.doi.org/10.1109/VISUAL.1993.398893',
 'http://dx.doi.org/10.1109/VISUAL.1993.398894',
 'http://dx.doi.org/10.1109/VISUAL.1993.398895',
 'http://dx.doi.org/10.1109/VISUAL.1993.398896',
 'http://dx.doi.org/10.1109/VISUAL.1993.398897',
 'http://dx.doi.org/10.1109/VISUAL.1993.398898',
 'http://dx.doi.org/10.1109/VISUAL.1993.398899',
 'http://dx.doi.org/10.1109/VISUAL.1993.398900',
 'http://dx.doi.org/10.1109/VISUAL.1993.398901',
 'http://dx.doi.org/10.1109/VISUAL.1993.398902',
 'http://dx.doi.org/10.1109/VISUAL.1993.398903',
 'http://dx.doi.org/10.1109/VISUAL.1993.398904',
 'http://dx.doi.org/10.1109/VISUAL.1993.398911',
 'http://dx.doi.org/10.1109/VISUAL.1994.346284',
 'http://dx.doi.org/10.1109/VISUAL.1994.346285',
 'http://dx.doi.org/10.1109/VISUAL.1994.346286',
 'http://dx.doi.org/10.1109/VISUAL.1994.346287',
 'http://dx.doi.org/10.1109/VISUAL.1994.346288',
 'http://dx.doi.org/10.1109/VISUAL.1994.346289',
 'http://dx.doi.org/10.1109/VISUAL.1994.346290',
 'http://dx.doi.org/10.1109/VISUAL.1994.346291',
 'http://dx.doi.org/10.1109/VISUAL.1994.346292',
 'http://dx.doi.org/10.1109/VISUAL.1994.346293',
 'http://dx.doi.org/10.1109/VISUAL.1994.346294',
 'http://dx.doi.org/10.1109/VISUAL.1994.346295',
 'http://dx.doi.org/10.1109/VISUAL.1994.346296',
 'http://dx.doi.org/10.1109/VISUAL.1994.346297',
 'http://dx.doi.org/10.1109/VISUAL.1994.346298',
 'http://dx.doi.org/10.1109/VISUAL.1994.346299',
 'http://dx.doi.org/10.1109/VISUAL.1994.346300',
 'http://dx.doi.org/10.1109/VISUAL.1994.346301',
 'http://dx.doi.org/10.1109/VISUAL.1994.346302',
 'http://dx.doi.org/10.1109/VISUAL.1994.346303',
 'http://dx.doi.org/10.1109/VISUAL.1994.346304',
 'http://dx.doi.org/10.1109/VISUAL.1994.346305',
 'http://dx.doi.org/10.1109/VISUAL.1994.346306',
 'http://dx.doi.org/10.1109/VISUAL.1994.346307',
 'http://dx.doi.org/10.1109/VISUAL.1994.346308',
 'http://dx.doi.org/10.1109/VISUAL.1994.346309',
 'http://dx.doi.org/10.1109/VISUAL.1994.346310',
 'http://dx.doi.org/10.1109/VISUAL.1994.346311',
 'http://dx.doi.org/10.1109/VISUAL.1994.346312',
 'http://dx.doi.org/10.1109/VISUAL.1994.346313',
 'http://dx.doi.org/10.1109/VISUAL.1994.346314',
 'http://dx.doi.org/10.1109/VISUAL.1994.346315',
 'http://dx.doi.org/10.1109/VISUAL.1994.346316',
 'http://dx.doi.org/10.1109/VISUAL.1994.346317',
 'http://dx.doi.org/10.1109/VISUAL.1994.346318',
 'http://dx.doi.org/10.1109/VISUAL.1994.346319',
 'http://dx.doi.org/10.1109/VISUAL.1994.346320',
 'http://dx.doi.org/10.1109/VISUAL.1994.346321',
 'http://dx.doi.org/10.1109/VISUAL.1994.346322',
 'http://dx.doi.org/10.1109/VISUAL.1994.346323',
 'http://dx.doi.org/10.1109/VISUAL.1994.346324',
 'http://dx.doi.org/10.1109/VISUAL.1994.346325',
 'http://dx.doi.org/10.1109/VISUAL.1994.346326',
 'http://dx.doi.org/10.1109/VISUAL.1994.346327',
 'http://dx.doi.org/10.1109/VISUAL.1994.346328',
 'http://dx.doi.org/10.1109/VISUAL.1994.346329',
 'http://dx.doi.org/10.1109/VISUAL.1994.346330',
 'http://dx.doi.org/10.1109/VISUAL.1994.346331',
 'http://dx.doi.org/10.1109/VISUAL.1994.346332',
 'http://dx.doi.org/10.1109/VISUAL.1994.346333',
 'http://dx.doi.org/10.1109/VISUAL.1994.346334',
 'http://dx.doi.org/10.1109/VISUAL.1994.346335',
 'http://dx.doi.org/10.1109/VISUAL.1994.346336',
 'http://dx.doi.org/10.1109/VISUAL.1994.346337',
 'http://dx.doi.org/10.1109/VISUAL.1994.346338',
 'http://dx.doi.org/10.1109/VISUAL.1994.346339',
 'http://dx.doi.org/10.1109/VISUAL.1994.346340',
 'http://dx.doi.org/10.1109/VISUAL.1994.346341',
 'http://dx.doi.org/10.1109/VISUAL.1994.346342',
 'http://dx.doi.org/10.1109/INFVIS.1995.528680',
 'http://dx.doi.org/10.1109/INFVIS.1995.528681',
 'http://dx.doi.org/10.1109/INFVIS.1995.528682',
 'http://dx.doi.org/10.1109/INFVIS.1995.528683',
 'http://dx.doi.org/10.1109/INFVIS.1995.528684',
 'http://dx.doi.org/10.1109/INFVIS.1995.528685',
 'http://dx.doi.org/10.1109/INFVIS.1995.528686',
 'http://dx.doi.org/10.1109/INFVIS.1995.528687',
 'http://dx.doi.org/10.1109/INFVIS.1995.528688',
 'http://dx.doi.org/10.1109/INFVIS.1995.528689',
 'http://dx.doi.org/10.1109/INFVIS.1995.528690',
 'http://dx.doi.org/10.1109/INFVIS.1995.528691',
 'http://dx.doi.org/10.1109/INFVIS.1995.528692',
 'http://dx.doi.org/10.1109/INFVIS.1995.528693',
 'http://dx.doi.org/10.1109/INFVIS.1995.528694',
 'http://dx.doi.org/10.1109/INFVIS.1995.528695',
 'http://dx.doi.org/10.1109/INFVIS.1995.528696',
 'http://dx.doi.org/10.1109/INFVIS.1995.528697',
 'http://dx.doi.org/10.1109/VISUAL.1995.480789',
 'http://dx.doi.org/10.1109/VISUAL.1995.480790',
 'http://dx.doi.org/10.1109/VISUAL.1995.480791',
 'http://dx.doi.org/10.1109/VISUAL.1995.480792',
 'http://dx.doi.org/10.1109/VISUAL.1995.480793',
 'http://dx.doi.org/10.1109/VISUAL.1995.480794',
 'http://dx.doi.org/10.1109/VISUAL.1995.480795',
 'http://dx.doi.org/10.1109/VISUAL.1995.480796',
 'http://dx.doi.org/10.1109/VISUAL.1995.480797',
 'http://dx.doi.org/10.1109/VISUAL.1995.480798',
 'http://dx.doi.org/10.1109/VISUAL.1995.480799',
 'http://dx.doi.org/10.1109/VISUAL.1995.480800',
 'http://dx.doi.org/10.1109/VISUAL.1995.480801',
 'http://dx.doi.org/10.1109/VISUAL.1995.480802',
 'http://dx.doi.org/10.1109/VISUAL.1995.480803',
 'http://dx.doi.org/10.1109/VISUAL.1995.480804',
 'http://dx.doi.org/10.1109/VISUAL.1995.480805',
 'http://dx.doi.org/10.1109/VISUAL.1995.480806',
 'http://dx.doi.org/10.1109/VISUAL.1995.480807',
 'http://dx.doi.org/10.1109/VISUAL.1995.480808',
 'http://dx.doi.org/10.1109/VISUAL.1995.480809',
 'http://dx.doi.org/10.1109/VISUAL.1995.480810',
 'http://dx.doi.org/10.1109/VISUAL.1995.480811',
 'http://dx.doi.org/10.1109/VISUAL.1995.480812',
 'http://dx.doi.org/10.1109/VISUAL.1995.480813',
 'http://dx.doi.org/10.1109/VISUAL.1995.480814',
 'http://dx.doi.org/10.1109/VISUAL.1995.480815',
 'http://dx.doi.org/10.1109/VISUAL.1995.480816',
 'http://dx.doi.org/10.1109/VISUAL.1995.480817',
 'http://dx.doi.org/10.1109/VISUAL.1995.480818',
 'http://dx.doi.org/10.1109/VISUAL.1995.480819',
 'http://dx.doi.org/10.1109/VISUAL.1995.480820',
 'http://dx.doi.org/10.1109/VISUAL.1995.480821',
 'http://dx.doi.org/10.1109/VISUAL.1995.485139',
 'http://dx.doi.org/10.1109/VISUAL.1995.485140',
 'http://dx.doi.org/10.1109/VISUAL.1995.485141',
 'http://dx.doi.org/10.1109/VISUAL.1995.485142',
 'http://dx.doi.org/10.1109/VISUAL.1995.485143',
 'http://dx.doi.org/10.1109/VISUAL.1995.485144',
 'http://dx.doi.org/10.1109/VISUAL.1995.485145',
 'http://dx.doi.org/10.1109/VISUAL.1995.485146',
 'http://dx.doi.org/10.1109/VISUAL.1995.485147',
 'http://dx.doi.org/10.1109/VISUAL.1995.485148',
 'http://dx.doi.org/10.1109/VISUAL.1995.485149',
 'http://dx.doi.org/10.1109/VISUAL.1995.485150',
 'http://dx.doi.org/10.1109/VISUAL.1995.485151',
 'http://dx.doi.org/10.1109/VISUAL.1995.485152',
 'http://dx.doi.org/10.1109/VISUAL.1995.485153',
 'http://dx.doi.org/10.1109/VISUAL.1995.485154',
 'http://dx.doi.org/10.1109/VISUAL.1995.485155',
 'http://dx.doi.org/10.1109/VISUAL.1995.485156',
 'http://dx.doi.org/10.1109/VISUAL.1995.485157',
 'http://dx.doi.org/10.1109/VISUAL.1995.485158',
 'http://dx.doi.org/10.1109/VISUAL.1995.485169',
 'http://dx.doi.org/10.1109/VISUAL.1995.485170',
 'http://dx.doi.org/10.1109/VISUAL.1995.485171',
 'http://dx.doi.org/10.1109/INFVIS.1996.559210',
 'http://dx.doi.org/10.1109/INFVIS.1996.559211',
 'http://dx.doi.org/10.1109/INFVIS.1996.559212',
 'http://dx.doi.org/10.1109/INFVIS.1996.559213',
 'http://dx.doi.org/10.1109/INFVIS.1996.559214',
 'http://dx.doi.org/10.1109/INFVIS.1996.559215',
 'http://dx.doi.org/10.1109/INFVIS.1996.559216',
 'http://dx.doi.org/10.1109/INFVIS.1996.559218',
 'http://dx.doi.org/10.1109/INFVIS.1996.559219',
 'http://dx.doi.org/10.1109/INFVIS.1996.559220',
 'http://dx.doi.org/10.1109/INFVIS.1996.559221',
 'http://dx.doi.org/10.1109/INFVIS.1996.559222',
 'http://dx.doi.org/10.1109/INFVIS.1996.559223',
 'http://dx.doi.org/10.1109/INFVIS.1996.559224',
 'http://dx.doi.org/10.1109/INFVIS.1996.559225',
 'http://dx.doi.org/10.1109/INFVIS.1996.559226',
 'http://dx.doi.org/10.1109/INFVIS.1996.559227',
 'http://dx.doi.org/10.1109/INFVIS.1996.559228',
 'http://dx.doi.org/10.1109/INFVIS.1996.559229',
 'http://dx.doi.org/10.1109/VISUAL.1996.567595',
 'http://dx.doi.org/10.1109/VISUAL.1996.567598',
 'http://dx.doi.org/10.1109/VISUAL.1996.567600',
 'http://dx.doi.org/10.1109/VISUAL.1996.567602',
 'http://dx.doi.org/10.1109/VISUAL.1996.567603',
 'http://dx.doi.org/10.1109/VISUAL.1996.567606',
 'http://dx.doi.org/10.1109/VISUAL.1996.567609',
 'http://dx.doi.org/10.1109/VISUAL.1996.567610',
 'http://dx.doi.org/10.1109/VISUAL.1996.567745',
 'http://dx.doi.org/10.1109/VISUAL.1996.567777',
 'http://dx.doi.org/10.1109/VISUAL.1996.567780',
 'http://dx.doi.org/10.1109/VISUAL.1996.567784',
 'http://dx.doi.org/10.1109/VISUAL.1996.567787',
 'http://dx.doi.org/10.1109/VISUAL.1996.567796',
 'http://dx.doi.org/10.1109/VISUAL.1996.567800',
 'http://dx.doi.org/10.1109/VISUAL.1996.567804',
 'http://dx.doi.org/10.1109/VISUAL.1996.567807',
 'http://dx.doi.org/10.1109/VISUAL.1996.567812',
 'http://dx.doi.org/10.1109/VISUAL.1996.568103',
 'http://dx.doi.org/10.1109/VISUAL.1996.568104',
 'http://dx.doi.org/10.1109/VISUAL.1996.568105',
 'http://dx.doi.org/10.1109/VISUAL.1996.568108',
 'http://dx.doi.org/10.1109/VISUAL.1996.568109',
 'http://dx.doi.org/10.1109/VISUAL.1996.568110',
 'http://dx.doi.org/10.1109/VISUAL.1996.568111',
 'http://dx.doi.org/10.1109/VISUAL.1996.568113',
 'http://dx.doi.org/10.1109/VISUAL.1996.568114',
 'http://dx.doi.org/10.1109/VISUAL.1996.568116',
 'http://dx.doi.org/10.1109/VISUAL.1996.568117',
 'http://dx.doi.org/10.1109/VISUAL.1996.568118',
 'http://dx.doi.org/10.1109/VISUAL.1996.568119',
 'http://dx.doi.org/10.1109/VISUAL.1996.568121',

In [11]:
con.sql("SELECT * FROM author")

┌────────────┬──────────────────────┐
│     id     │         name         │
│   int64    │       varchar        │
├────────────┼──────────────────────┤
│ 5071520966 │ James L. Helman      │
│ 5110998886 │ L. Hesselink         │
│ 5006450303 │ Gordon Bancroft      │
│ 5083931343 │ F. Merritt           │
│ 5030050956 │ Todd Plessel         │
│ 5089904045 │ Paul G. Kelaita      │
│ 5067876179 │ R. Kevin McCabe      │
│ 5073465792 │ Al Globus            │
│ 5046609142 │ B. Hibbard           │
│ 5070589478 │ David Santek         │
│      ·     │      ·               │
│      ·     │      ·               │
│      ·     │      ·               │
│ 5010847113 │ Po-Ming Law          │
│ 5051526027 │ Wenchao Wu           │
│ 5108098662 │ Yixian Zheng         │
│ 5091466289 │ Huamin Qu            │
│ 5012158528 │ Sriram Karthik Badam │
│ 5061444760 │ Fereshteh Amini      │
│ 5034277315 │ Niklas Elmqvist      │
│ 5078907679 │ Pourang Irani        │
│ 5061027107 │ Florian Heimerl      │
│ 5112771943 │ Markus John          │
├────────────┴──────────────────────┤
│   ? rows (>9999 rows, 20 shown)   │
└───────────────────────────────────┘

In [12]:
con.sql("SELECT * FROM paper")

┌────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────┬──────────────────┬───────────────────────────────────────────────────────────────────────────────────────┬──────────┬───────────┐
│     id     │                                                         title                                                          │                    doi                     │ publication_date │                                        oa_url                                         │ pdf_path │  inst_id  │
│   int64    │                                                        varchar                                                         │                  varchar                   │       date       │                                        varchar                                        │ varchar  │   int64   │
├────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼──────────────────┼───────────────────────────────────────────────────────────────────────────────────────┼──────────┼───────────┤
│ 3085563693 │ Surface representations of two- and three-dimensional fluid flow topology                                              │ https://doi.org/10.1109/visual.1990.146359 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 3041520455 │ FAST: a multi-processed environment for visualization of computational fluid dynamics                                  │ https://doi.org/10.1109/visual.1990.146360 │ 2002-12-04       │ https://jaxa.repo.nii.ac.jp/record/43435/files/nalsp0014002.pdf                       │ NULL     │ 138006243 │
│ 4237685258 │ The VIS-5D system for easy interactive visualization                                                                   │ https://doi.org/10.1109/visual.1990.146361 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4241306103 │ A procedural interface for volume rendering                                                                            │ https://doi.org/10.1109/visual.1990.146362 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4242274056 │ Techniques for the interactive visualization of volumetric data                                                        │ https://doi.org/10.1109/visual.1990.146363 │ 2002-12-04       │ https://escholarship.org/content/qt4367m3t4/qt4367m3t4.pdf?t=ptt2h6                   │ NULL     │ 138006243 │
│ 4235544651 │ Displaying voxel-based objects according to their qualitative shape synthesis                                          │ https://doi.org/10.1109/visual.1990.146364 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4243289651 │ Interpreting a 3D object from a rough 2D line drawing                                                                  │ https://doi.org/10.1109/visual.1990.146365 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4232108933 │ Animation techniques for chain-coded objects                                                                           │ https://doi.org/10.1109/visual.1990.146366 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4239445310 │ Extracting geometric models through constraint minimization                                                            │ https://doi.org/10.1109/visual.1990.146367 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4252612379 │ Wide-band relativistic Doppler effect visualization                                                                    │ https://doi.org/10.1109/visual.1990.146368 │ 2002-12-04       │ http://www.ri.cmu.edu/pub_files/pub2/hsiung_p_k_1990_1/hsiung_p_k_1990_1.pdf          │ NULL     │ 138006243 │
│      ·     │                          ·                                                                                             │                     ·                      │     ·            │                     ·                                                                 │  ·       │     ·     │
│      ·     │                          ·                                                                                             │                     ·                      │     ·            │                     ·                                                                 │  ·       │     ·     │
│      ·     │                          ·                                                                                             │                     ·                      │     ·            │                     ·                                                                 │  ·       │     ·     │
│ 2894279555 │ Situ: Identifying and Explaining Suspicious Behavior in Networks                                                       │ https://doi.org/10.1109/tvcg.2018.2865029  │ 2018-08-20       │ https://www.osti.gov/servlets/purl/1486963                                            │ NULL     │ 138006243 │
│ 2896091756 │ Enhancing Web-based Analytics Applications through Provenance                                                          │ https://doi.org/10.1109/tvcg.2018.2865039  │ 2018-10-19       │ None                                                                                  │ NULL     │ 138006243 │
│ 2904955348 │ Futzing and Moseying: Interviews with Professional Data Analysts on Exploration Practices                              │ https://doi.org/10.1109/tvcg.2018.2865040  │ 2018-08-20       │ https://escholarship.org/content/qt04g0z5gn/qt04g0z5gn.pdf?t=pvt8ml                   │ NULL     │ 138006243 │
│ 2888032845 │ ForVizor: Visualizing Spatio-Temporal Team Formations in Soccer                                                        │ https://doi.org/10.1109/tvcg.2018.2865041  │ 2018-08-20       │ None                                                                                  │ NULL     │ 138006243 │
│ 2890529371 │ Identification of Temporally Varying Areas of Interest in Long-Duration Eye-Tracking Data Sets                         │ https://doi.org/10.1109/tvcg.2018.2865042  │ 2018-09-03       │ None                                                                                  │ NULL     │ 138006243 │
│ 2889730816 │ RegressionExplorer: Interactive Exploration of Logistic Regression Models with Subgroup Analysis                       │ https://doi.org/10.1109/tvcg.2018.2865043  │ 2018-09-13       │ https://pure.tue.nl/ws/files/116894719/08464305.pdf                                   │ NULL     │ 138006243 │
│ 2963123635 │ Seq2seq-Vis: A Visual Debugging Tool for Sequence-to-Sequence Models                                                   │ https://doi.org/10.1109/tvcg.2018.2865044  │ 2018-10-17       │ https://arxiv.org/pdf/1804.09299                                                      │ NULL     │ 138006243 │
│ 2888244365 │ SIRIUS: Dual, Symmetric, Interactive Dimension Reductions                                                              │ https://doi.org/10.1109/tvcg.2018.2865047  │ 2018-08-20       │ None                                                                                  │ NULL     │ 138006243 │
│ 2888207115 │ MotionRugs: Visualizing Collective Trends in Space and Time                                                            │ https://doi.org/10.1109/tvcg.2018.2865049  │ 2018-08-20       │ https://kops.uni-konstanz.de/bitstreams/6238ff7a-1096-4aae-8144-4c2cd238c198/download │ NULL     │ 138006243 │
│ 2886794935 │ Drag and Track: A Direct Manipulation Interface for Contextualizing Data Instances within a Continuous Parameter Space │ https://doi.org/10.1109/tvcg.2018.2865051  │ 2018-08-20       │ None                                                                                  │ NULL     │ 138006243 │
├────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────┴──────────────────┴───────────────────────────────────────────────────────────────────────────────────────┴──────────┴───────────┤
│ 3053 rows (20 shown)                                                                                                                                                                                                                                                                                     7 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [13]:
con.sql("SELECT * FROM institution").show()

┌────────────┬───────────┬──────────────────────────────────────────────┐
│     id     │    ror    │                     name                     │
│   int64    │  varchar  │                   varchar                    │
├────────────┼───────────┼──────────────────────────────────────────────┤
│  138006243 │ 03m2x1q45 │ University of Arizona                        │
│   97018004 │ 00f54p054 │ Stanford University                          │
│   13805885 │ 056e22e24 │ Vaughn College of Aeronautics and Technology │
│ 4210153694 │ 049ba1e57 │ Rho (United States)                          │
│  135310074 │ 01y2jtd41 │ University of Wisconsin–Madison              │
│  126533617 │ 04k8zab17 │ Alliant International University             │
│   55732556 │ 03efmqc40 │ Arizona State University                     │
│   66946132 │ 047s2c258 │ University of Maryland, College Park         │
│   59553526 │ 05qghxh33 │ Stony Brook University                       │
│ 1327163397 │ 01q1z8k08 │ State University of New York                 │
│      ·     │     ·     │            ·                                 │
│      ·     │     ·     │            ·                                 │
│      ·     │     ·     │            ·                                 │
│ 2946016260 │ 05vm0ed18 │ Uber AI (United States)                      │
│ 1328775524 │ 03893we55 │ Zhejiang Sci-Tech University                 │
│ 4210092639 │ 00fxnmt68 │ Boeing (Spain)                               │
│  134113660 │ 01keh0577 │ University of Nevada, Reno                   │
│  179026463 │ 013e0zm98 │ Beijing Technology and Business University   │
│ 4210095624 │ 00rn0m335 │ Alibaba Group (United States)                │
│ 4390039371 │ 018nc6029 │ Solutions Inc. (Japan)                       │
│ 4210119669 │ 026vtvm28 │ Boehringer Ingelheim (Austria)               │
│   67900169 │ 01r024a98 │ Chung-Ang University                         │
│   39705031 │ 04fxknd68 │ Catholic University of Daegu                 │
├────────────┴───────────┴──────────────────────────────────────────────┤
│ 1033 rows (20 shown)                                        3 columns │
└───────────────────────────────────────────────────────────────────────┘

In [31]:
con.close()

In [5]:
import duckdb as db

In [6]:
con = db.connect("./visimages.db")

In [33]:
con.execute("EXPORT DATABASE 'vis-parquet' (FORMAT parquet);")

In [7]:
papers = con.sql("SELECT * FROM paper").df()

In [10]:
papers.iloc[285]

id                                                         1970929543
title               Research report: information animation applica...
doi                        https://doi.org/10.1109/infvis.1995.528682
publication_date                                  2002-11-19 00:00:00
oa_url                                                           None
pdf_path                                                         None
inst_id                                                     138006243
Name: 285, dtype: object