In [3]:
import duckdb as db

In [5]:
from pathlib import Path
import json
import numpy as np

arrays = sorted(Path("outputs").glob("*.json"))

In [41]:
len(arrays)

10000

In [6]:
connection = db.connect("publications_princeton.36608975.db")

connection.sql("SHOW TABLES")

connection.sql("SELECT * FROM figure_property")

connection.sql("DESCRIBE figure")

paths = connection.sql("SELECT server_path FROM figure")

from pathlib import Path

figure_id_ordered_paths = [f"array_fig-{Path(pth).parent.name}-{Path(pth).stem}.json" for pth in paths.df().server_path]

figure_id_ordered_paths[0]

exists_check = [Path(f"outputs/{p}").exists() for p in figure_id_ordered_paths]

# check to see how many figures in the table weren't chart typed
sum([not Path(f"outputs/{p}").exists() for p in figure_id_ordered_paths])

# now create an array that maps from the order in the figure_id_ordered_paths to the indices of the original json arrays list which we built the arrays fr
lookup_map = {str(e.name):i for i,e in enumerate(arrays)}

arrays[:5]

exists_check[:5]

# example for getting the index in our result array for the figure who's table id is 0
ex_figure_id_0 =figure_id_ordered_paths[0]
print(ex_figure_id_0)
array_index = lookup_map[ex_figure_id_0]
print(array_index)
# then we can use that same index to pull out the x,y,z coordinates that are supposed to replace the existing ones

array_fig-4281966491-Figure1-1.json
6217

In [52]:
connection.sql("SELECT id,server_path FROM figure")

┌───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  id   │                                                 server_path                                                  │
│ int64 │                                                   varchar                                                    │
├───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     0 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4281966491/Figure1-1.…  │
│     3 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4210714446/Figure10-1…  │
│     6 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4210714446/Figure6-1.…  │
│     9 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4210714446/Figure1-1.…  │
│    12 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4210714446/Figure4-1.…  │
│    15 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4210714446/Figure2-1.…  │
│    18 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4210714446/Figure9-1.…  │
│    21 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4210714446/Figure7-1.…  │
│    24 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4210714446/Figure3-1.…  │
│    27 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4210714446/Figure8-1.…  │
│     · │                                                      ·                                                       │
│     · │                                                      ·                                                       │
│     · │                                                      ·                                                       │
│  9990 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4285591978/Figure6-1.…  │
│  9991 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4285591978/Figure7-1.…  │
│  9992 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4285591978/Figure8-1.…  │
│  9993 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4285728040/Figure1-1.…  │
│  9994 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4285728040/Figure2-1.…  │
│  9995 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4285728040/Figure3-1.…  │
│  9996 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4285728040/Figure4-1.…  │
│  9997 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4285730332/Figure1-1.…  │
│  9998 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4285730332/Figure2-1.…  │
│  9999 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/Princeton_content/4285731161/Figure2-1.…  │
├───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                              2 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [47]:
lookup_map

{'array_fig-2340671844-Figure1-1.json': 0,
 'array_fig-2340671844-Figure10-1.json': 1,
 'array_fig-2340671844-Figure11-1.json': 2,
 'array_fig-2340671844-Figure12-1.json': 3,
 'array_fig-2340671844-Figure13-1.json': 4,
 'array_fig-2340671844-Figure14-1.json': 5,
 'array_fig-2340671844-Figure15-1.json': 6,
 'array_fig-2340671844-Figure16-1.json': 7,
 'array_fig-2340671844-Figure17-1.json': 8,
 'array_fig-2340671844-Figure18-1.json': 9,
 'array_fig-2340671844-Figure19-1.json': 10,
 'array_fig-2340671844-Figure2-1.json': 11,
 'array_fig-2340671844-Figure20-1.json': 12,
 'array_fig-2340671844-Figure21-1.json': 13,
 'array_fig-2340671844-Figure22-1.json': 14,
 'array_fig-2340671844-Figure23-1.json': 15,
 'array_fig-2340671844-Figure24-1.json': 16,
 'array_fig-2340671844-Figure25-1.json': 17,
 'array_fig-2340671844-Figure26-1.json': 18,
 'array_fig-2340671844-Figure27-1.json': 19,
 'array_fig-2340671844-Figure28-1.json': 20,
 'array_fig-2340671844-Figure29-1.json': 21,
 'array_fig-2340671844-Figure3-1.json': 22,
 'array_fig-2340671844-Figure30-1.json': 23,
 'array_fig-2340671844-Figure31-1.json': 24,
 'array_fig-2340671844-Figure32-1.json': 25,
 'array_fig-2340671844-Figure33-1.json': 26,
 'array_fig-2340671844-Figure36-1.json': 27,
 'array_fig-2340671844-Figure37-1.json': 28,
 'array_fig-2340671844-Figure38-1.json': 29,
 'array_fig-2340671844-Figure39-1.json': 30,
 'array_fig-2340671844-Figure4-1.json': 31,
 'array_fig-2340671844-Figure40-1.json': 32,
 'array_fig-2340671844-Figure41-1.json': 33,
 'array_fig-2340671844-Figure42-1.json': 34,
 'array_fig-2340671844-Figure43-1.json': 35,
 'array_fig-2340671844-Figure44-1.json': 36,
 'array_fig-2340671844-Figure45-1.json': 37,
 'array_fig-2340671844-Figure46-1.json': 38,
 'array_fig-2340671844-Figure48-1.json': 39,
 'array_fig-2340671844-Figure49-1.json': 40,
 'array_fig-2340671844-Figure5-1.json': 41,
 'array_fig-2340671844-Figure50-1.json': 42,
 'array_fig-2340671844-Figure51-1.json': 43,
 'array_fig-2340671844-Figure52-1.json': 44,
 'array_fig-2340671844-Figure53-1.json': 45,
 'array_fig-2340671844-Figure54-1.json': 46,
 'array_fig-2340671844-Figure55-1.json': 47,
 'array_fig-2340671844-Figure56-1.json': 48,
 'array_fig-2340671844-Figure57-1.json': 49,
 'array_fig-2340671844-Figure58-1.json': 50,
 'array_fig-2340671844-Figure59-1.json': 51,
 'array_fig-2340671844-Figure6-1.json': 52,
 'array_fig-2340671844-Figure60-1.json': 53,
 'array_fig-2340671844-Figure61-1.json': 54,
 'array_fig-2340671844-Figure62-1.json': 55,
 'array_fig-2340671844-Figure63-1.json': 56,
 'array_fig-2340671844-Figure7-1.json': 57,
 'array_fig-2340671844-Figure8-1.json': 58,
 'array_fig-2340671844-Figure9-1.json': 59,
 'array_fig-2399564276-Figure1-1.json': 60,
 'array_fig-2399564276-Figure2-1.json': 61,
 'array_fig-2399564276-Figure3-1.json': 62,
 'array_fig-2399564276-Figure4-1.json': 63,
 'array_fig-2510179618-Figure10-1.json': 64,
 'array_fig-2510179618-Figure11-1.json': 65,
 'array_fig-2510179618-Figure12-1.json': 66,
 'array_fig-2510179618-Figure13-1.json': 67,
 'array_fig-2510179618-Figure14-1.json': 68,
 'array_fig-2510179618-Figure15-1.json': 69,
 'array_fig-2510179618-Figure16-1.json': 70,
 'array_fig-2510179618-Figure17-1.json': 71,
 'array_fig-2510179618-Figure18-1.json': 72,
 'array_fig-2510179618-Figure19-1.json': 73,
 'array_fig-2510179618-Figure2-1.json': 74,
 'array_fig-2510179618-Figure20-1.json': 75,
 'array_fig-2510179618-Figure21-1.json': 76,
 'array_fig-2510179618-Figure22-1.json': 77,
 'array_fig-2510179618-Figure23-1.json': 78,
 'array_fig-2510179618-Figure24-1.json': 79,
 'array_fig-2510179618-Figure25-1.json': 80,
 'array_fig-2510179618-Figure26-1.json': 81,
 'array_fig-2510179618-Figure27-1.json': 82,
 'array_fig-2510179618-Figure28-1.json': 83,
 'array_fig-2510179618-Figure29-1.json': 84,
 'array_fig-2510179618-Figure3-1.json': 85,
 'array_fig-2510179618-Figure30-1.json': 86,
 'array_fig-2510179618-Figure31-1.json': 87,
 'array_fig-2510179618-Figure32-1.json': 88,
 'array_fig-2510179618-Figure33-1.json': 89,
 'array_fig-2510179618-Figure34-1.json': 90,
 'array_fig-2510179618-Figure35-1.json': 91,
 'array_fig-2510179618-Figure36-1.json': 92,
 'array_fig-2510179618-Figure37-1.json': 93,
 'array_fig-2510179618-Figure38-1.json': 94,
 'array_fig-2510179618-Figure39-1.json': 95,
 'array_fig-2510179618-Figure4-1.json': 96,
 'array_fig-2510179618-Figure40-1.json': 97,
 'array_fig-2510179618-Figure41-1.json': 98,
 'array_fig-2510179618-Figure42-1.json': 99,
 'array_fig-2510179618-Figure43-1.json': 100,
 'array_fig-2510179618-Figure44-1.json': 101,
 'array_fig-2510179618-Figure45-1.json': 102,
 'array_fig-2510179618-Figure46-1.json': 103,
 'array_fig-2510179618-Figure47-1.json': 104,
 'array_fig-2510179618-Figure48-1.json': 105,
 'array_fig-2510179618-Figure49-1.json': 106,
 'array_fig-2510179618-Figure5-1.json': 107,
 'array_fig-2510179618-Figure50-1.json': 108,
 'array_fig-2510179618-Figure51-1.json': 109,
 'array_fig-2510179618-Figure52-1.json': 110,
 'array_fig-2510179618-Figure53-1.json': 111,
 'array_fig-2510179618-Figure54-1.json': 112,
 'array_fig-2510179618-Figure55-1.json': 113,
 'array_fig-2510179618-Figure56-1.json': 114,
 'array_fig-2510179618-Figure57-1.json': 115,
 'array_fig-2510179618-Figure58-1.json': 116,
 'array_fig-2510179618-Figure59-1.json': 117,
 'array_fig-2510179618-Figure6-1.json': 118,
 'array_fig-2510179618-Figure60-1.json': 119,
 'array_fig-2510179618-Figure61-1.json': 120,
 'array_fig-2510179618-Figure62-1.json': 121,
 'array_fig-2510179618-Figure63-1.json': 122,
 'array_fig-2510179618-Figure64-1.json': 123,
 'array_fig-2510179618-Figure65-1.json': 124,
 'array_fig-2510179618-Figure66-1.json': 125,
 'array_fig-2510179618-Figure67-1.json': 126,
 'array_fig-2510179618-Figure68-1.json': 127,
 'array_fig-2510179618-Figure69-1.json': 128,
 'array_fig-2510179618-Figure7-1.json': 129,
 'array_fig-2510179618-Figure8-1.json': 130,
 'array_fig-2510179618-Figure9-1.json': 131,
 'array_fig-2516782548-Figure1-1.json': 132,
 'array_fig-2516782548-Figure2-1.json': 133,
 'array_fig-2516782548-Figure3-1.json': 134,
 'array_fig-2516782548-Figure4-1.json': 135,
 'array_fig-2516782548-Figure5-1.json': 136,
 'array_fig-2883397413-Figure1-1.json': 137,
 'array_fig-2903984611-Figure2-1.json': 138,
 'array_fig-2917246580-Figure1-1.json': 139,
 'array_fig-2917246580-Figure10-1.json': 140,
 'array_fig-2917246580-Figure11-1.json': 141,
 'array_fig-2917246580-Figure2-1.json': 142,
 'array_fig-2917246580-Figure3-1.json': 143,
 'array_fig-2917246580-Figure4-1.json': 144,
 'array_fig-2917246580-Figure5-1.json': 145,
 'array_fig-2917246580-Figure6-1.json': 146,
 'array_fig-2917246580-Figure7-1.json': 147,
 'array_fig-2917246580-Figure8-1.json': 148,
 'array_fig-2917246580-Figure9-1.json': 149,
 'array_fig-2948579940-Figure1-1.json': 150,
 'array_fig-2948579940-Figure2-1.json': 151,
 'array_fig-2948579940-Figure3-1.json': 152,
 'array_fig-2953880153-Figure1-1.json': 153,
 'array_fig-2953880153-Figure2-1.json': 154,
 'array_fig-2953880153-Figure3-1.json': 155,
 'array_fig-2953880153-Figure4-1.json': 156,
 'array_fig-2953880153-Figure5-1.json': 157,
 'array_fig-2953880153-Figure6-1.json': 158,
 'array_fig-2953880153-Figure7-1.json': 159,
 'array_fig-2953880153-Figure8-1.json': 160,
 'array_fig-2978782546-Figure1-1.json': 161,
 'array_fig-2978782546-Figure2-1.json': 162,
 'array_fig-2978782546-Figure3-1.json': 163,
 'array_fig-2978782546-Figure4-1.json': 164,
 'array_fig-2980000635-Figure1-1.json': 165,
 'array_fig-2980000635-Figure2-1.json': 166,
 'array_fig-2980000635-Figure3-1.json': 167,
 'array_fig-2980000635-Figure5-1.json': 168,
 'array_fig-2980000635-Figure6-1.json': 169,
 'array_fig-2982324007-Figure2-1.json': 170,
 'array_fig-2982324007-Figure3-1.json': 171,
 'array_fig-2982324007-Figure4-1.json': 172,
 'array_fig-2982324007-Figure5-1.json': 173,
 'array_fig-2982333300-Figure1-1.json': 174,
 'array_fig-2982333300-Figure10-1.json': 175,
 'array_fig-2982333300-Figure11-1.json': 176,
 'array_fig-2982333300-Figure12-1.json': 177,
 'array_fig-2982333300-Figure13-1.json': 178,
 'array_fig-2982333300-Figure14-1.json': 179,
 'array_fig-2982333300-Figure15-1.json': 180,
 'array_fig-2982333300-Figure16-1.json': 181,
 'array_fig-2982333300-Figure17-1.json': 182,
 'array_fig-2982333300-Figure18-1.json': 183,
 'array_fig-2982333300-Figure2-1.json': 184,
 'array_fig-2982333300-Figure3-1.json': 185,
 'array_fig-2982333300-Figure4-1.json': 186,
 'array_fig-2982333300-Figure5-1.json': 187,
 'array_fig-2982333300-Figure6-1.json': 188,
 'array_fig-2982333300-Figure7-1.json': 189,
 'array_fig-2982333300-Figure8-1.json': 190,
 'array_fig-2982333300-Figure9-1.json': 191,
 'array_fig-2989360195-Figure1-1.json': 192,
 'array_fig-2989360195-Figure2-1.json': 193,
 'array_fig-2989360195-Figure3-1.json': 194,
 'array_fig-2989360195-Figure4-1.json': 195,
 'array_fig-2997451176-Figure1-1.json': 196,
 'array_fig-2997451176-Figure2-1.json': 197,
 'array_fig-3000625380-Figure5-1.json': 198,
 'array_fig-3004250597-Figure1-1.json': 199,
 'array_fig-3004250597-Figure2-1.json': 200,
 'array_fig-3004250597-Figure3-1.json': 201,
 'array_fig-3004250597-Figure4-1.json': 202,
 'array_fig-3004250597-Figure5-1.json': 203,
 'array_fig-3005576178-Figure1-1.json': 204,
 'array_fig-3005576178-Figure2-1.json': 205,
 'array_fig-3008463181-Figure1-1.json': 206,
 'array_fig-3008463181-Figure10-1.json': 207,
 'array_fig-3008463181-Figure2-1.json': 208,
 'array_fig-3008463181-Figure3-1.json': 209,
 'array_fig-3008463181-Figure4-1.json': 210,
 'array_fig-3008463181-Figure5-1.json': 211,
 'array_fig-3008463181-Figure6-1.json': 212,
 'array_fig-3008463181-Figure7-1.json': 213,
 'array_fig-3008463181-Figure8-1.json': 214,
 'array_fig-3008463181-Figure9-1.json': 215,
 'array_fig-3009522687-Figure1-1.json': 216,
 'array_fig-3009522687-Figure2-1.json': 217,
 'array_fig-3009742497-Figure1-1.json': 218,
 'array_fig-3009742497-Figure2-1.json': 219,
 'array_fig-3009742497-Figure3-1.json': 220,
 'array_fig-3009742497-Figure4-1.json': 221,
 'array_fig-3009742497-Figure5-1.json': 222,
 'array_fig-3009742497-Figure6-1.json': 223,
 'array_fig-3009742497-Figure7-1.json': 224,
 'array_fig-3009742497-Figure8-1.json': 225,
 'array_fig-3009742497-Figure9-1.json': 226,
 'array_fig-3011923337-Figure1-1.json': 227,
 'array_fig-3011923337-Figure2-1.json': 228,
 'array_fig-3011923337-Figure3-1.json': 229,
 'array_fig-3013671361-Figure1-1.json': 230,
 'array_fig-3013671361-Figure2-1.json': 231,
 'array_fig-3018002705-Figure1-1.json': 232,
 'array_fig-3018002705-Figure2-1.json': 233,
 'array_fig-3018002705-Figure3-1.json': 234,
 'array_fig-3018002705-Figure4-1.json': 235,
 'array_fig-3018002705-Figure5-1.json': 236,
 'array_fig-3018002705-Figure6-1.json': 237,
 'array_fig-3021385523-Figure1-1.json': 238,
 'array_fig-3021385523-Figure2-1.json': 239,
 'array_fig-3021385523-Figure3-1.json': 240,
 'array_fig-3021385523-Figure4-1.json': 241,
 'array_fig-3021385523-Figure5-1.json': 242,
 'array_fig-3022153899-Figure1-1.json': 243,
 'array_fig-3035183408-Figure1-1.json': 244,
 'array_fig-3036075322-Figure1-1.json': 245,
 'array_fig-3036075322-Figure2-1.json': 246,
 'array_fig-3036075322-Figure3-1.json': 247,
 'array_fig-3036075322-Figure4-1.json': 248,
 'array_fig-3036370159-Figure1-1.json': 249,
 'array_fig-3036370159-Figure2-1.json': 250,
 'array_fig-3036370159-Figure3-1.json': 251,
 'array_fig-3036370159-Figure5-1.json': 252,
 'array_fig-3038093235-Figure1-1.json': 253,
 'array_fig-3038093235-Figure10-1.json': 254,
 'array_fig-3038093235-Figure11-1.json': 255,
 'array_fig-3038093235-Figure16-1.json': 256,
 'array_fig-3038093235-Figure2-1.json': 257,
 'array_fig-3038093235-Figure22-1.json': 258,
 'array_fig-3038093235-Figure3-1.json': 259,
 'array_fig-3038093235-Figure4-1.json': 260,
 'array_fig-3038093235-Figure5-1.json': 261,
 'array_fig-3038093235-Figure6-1.json': 262,
 'array_fig-3038093235-Figure7-1.json': 263,
 'array_fig-3038093235-Figure8-1.json': 264,
 'array_fig-3038093235-Figure9-1.json': 265,
 'array_fig-3041392591-Figure1-1.json': 266,
 'array_fig-3041392591-Figure10-1.json': 267,
 'array_fig-3041392591-Figure2-1.json': 268,
 'array_fig-3041392591-Figure3-1.json': 269,
 'array_fig-3041392591-Figure4-1.json': 270,
 'array_fig-3041392591-Figure5-1.json': 271,
 'array_fig-3041392591-Figure6-1.json': 272,
 'array_fig-3041392591-Figure7-1.json': 273,
 'array_fig-3041392591-Figure8-1.json': 274,
 'array_fig-3041392591-Figure9-1.json': 275,
 'array_fig-3043392521-Figure1-1.json': 276,
 'array_fig-3043392521-Figure2-1.json': 277,
 'array_fig-3044968142-Figure1-1.json': 278,
 'array_fig-3044968142-Figure2-1.json': 279,
 'array_fig-3044968142-Figure3-1.json': 280,
 'array_fig-3044968142-Figure4-1.json': 281,
 'array_fig-3044968142-Figure5-1.json': 282,
 'array_fig-3044968142-Figure6-1.json': 283,
 'array_fig-3044968142-Figure7-1.json': 284,
 'array_fig-3048426687-Figure1-1.json': 285,
 'array_fig-3052291153-Figure1-1.json': 286,
 'array_fig-3080826078-Figure1-1.json': 287,
 'array_fig-3080826078-Figure10-1.json': 288,
 'array_fig-3080826078-Figure11-1.json': 289,
 'array_fig-3080826078-Figure12-1.json': 290,
 'array_fig-3080826078-Figure13-1.json': 291,
 'array_fig-3080826078-Figure14-1.json': 292,
 'array_fig-3080826078-Figure15-1.json': 293,
 'array_fig-3080826078-Figure2-1.json': 294,
 'array_fig-3080826078-Figure4-1.json': 295,
 'array_fig-3080826078-Figure8-1.json': 296,
 'array_fig-3080826078-Figure9-1.json': 297,
 'array_fig-3082127980-Figure1-1.json': 298,
 'array_fig-3082127980-Figure2-1.json': 299,
 'array_fig-3082127980-Figure3-1.json': 300,
 'array_fig-3082127980-Figure4-1.json': 301,
 'array_fig-3082127980-Figure5-1.json': 302,
 'array_fig-3082127980-Figure6-1.json': 303,
 'array_fig-3082127980-Figure7-1.json': 304,
 'array_fig-3082127980-Figure8-1.json': 305,
 'array_fig-3084143938-Figure1-1.json': 306,
 'array_fig-3084143938-Figure2-1.json': 307,
 'array_fig-3084143938-Figure3-1.json': 308,
 'array_fig-3090924138-Figure1-1.json': 309,
 'array_fig-3090924138-Figure3-1.json': 310,
 'array_fig-3092500000-Figure1-1.json': 311,
 'array_fig-3092500000-Figure2-1.json': 312,
 'array_fig-3092500000-Figure3-1.json': 313,
 'array_fig-3092500000-Figure4-1.json': 314,
 'array_fig-3093650263-Figure1-1.json': 315,
 'array_fig-3093650263-Figure2-1.json': 316,
 'array_fig-3093650263-Figure3-1.json': 317,
 'array_fig-3093650263-Figure4-1.json': 318,
 'array_fig-3094513744-Figure1-1.json': 319,
 'array_fig-3095647601-Figure1-1.json': 320,
 'array_fig-3095647601-Figure2-1.json': 321,
 'array_fig-3095647601-Figure3-1.json': 322,
 'array_fig-3095647601-Figure5-1.json': 323,
 'array_fig-3095647601-Figure6-1.json': 324,
 'array_fig-3095682039-Figure1-1.json': 325,
 'array_fig-3095682039-Figure10-1.json': 326,
 'array_fig-3095682039-Figure11-1.json': 327,
 'array_fig-3095682039-Figure12-1.json': 328,
 'array_fig-3095682039-Figure13-1.json': 329,
 'array_fig-3095682039-Figure14-1.json': 330,
 'array_fig-3095682039-Figure15-1.json': 331,
 'array_fig-3095682039-Figure16-1.json': 332,
 'array_fig-3095682039-Figure17-1.json': 333,
 'array_fig-3095682039-Figure18-1.json': 334,
 'array_fig-3095682039-Figure2-1.json': 335,
 'array_fig-3095682039-Figure3-1.json': 336,
 'array_fig-3095682039-Figure4-1.json': 337,
 'array_fig-3095682039-Figure5-1.json': 338,
 'array_fig-3095682039-Figure6-1.json': 339,
 'array_fig-3095682039-Figure7-1.json': 340,
 'array_fig-3095682039-Figure8-1.json': 341,
 'array_fig-3095682039-Figure9-1.json': 342,
 'array_fig-3095925971-Figure1-1.json': 343,
 'array_fig-3096572172-Figure1.1-1.json': 344,
 'array_fig-3096572172-Figure1.10-1.json': 345,
 'array_fig-3096572172-Figure1.11-1.json': 346,
 'array_fig-3096572172-Figure1.12-1.json': 347,
 'array_fig-3096572172-Figure1.2-1.json': 348,
 'array_fig-3096572172-Figure1.3-1.json': 349,
 'array_fig-3096572172-Figure1.4-1.json': 350,
 'array_fig-3096572172-Figure1.5-1.json': 351,
 'array_fig-3096572172-Figure1.6-1.json': 352,
 'array_fig-3096572172-Figure1.7-1.json': 353,
 'array_fig-3096572172-Figure1.8-1.json': 354,
 'array_fig-3096572172-Figure1.9-1.json': 355,
 'array_fig-3098718496-Figure2-1.json': 356,
 'array_fig-3098718496-Figure4-1.json': 357,
 'array_fig-3111728169-Figure11-1.json': 358,
 'array_fig-3111728169-Figure12-1.json': 359,
 'array_fig-3111728169-Figure13-1.json': 360,
 'array_fig-3111728169-Figure7-1.json': 361,
 'array_fig-3111728169-Figure8-1.json': 362,
 'array_fig-3111728169-Figure9-1.json': 363,
 'array_fig-3120336817-Figure1.1-1.json': 364,
 'array_fig-3120336817-Figure1.10-1.json': 365,
 'array_fig-3120336817-Figure1.11-1.json': 366,
 'array_fig-3120336817-Figure1.12-1.json': 367,
 'array_fig-3120336817-Figure1.13-1.json': 368,
 'array_fig-3120336817-Figure1.14-1.json': 369,
 'array_fig-3120336817-Figure1.15-1.json': 370,
 'array_fig-3120336817-Figure1.16-1.json': 371,
 'array_fig-3120336817-Figure1.2-1.json': 372,
 'array_fig-3120336817-Figure1.3-1.json': 373,
 'array_fig-3120336817-Figure1.4-1.json': 374,
 'array_fig-3120336817-Figure1.5-1.json': 375,
 'array_fig-3120336817-Figure1.6-1.json': 376,
 'array_fig-3120336817-Figure1.7-1.json': 377,
 'array_fig-3120336817-Figure1.8-1.json': 378,
 'array_fig-3120336817-Figure1.9-1.json': 379,
 'array_fig-3120702333-Figure1-1.json': 380,
 'array_fig-3120702333-Figure2-1.json': 381,
 'array_fig-3120702333-Figure3-1.json': 382,
 'array_fig-3120702333-Figure5-1.json': 383,
 'array_fig-3120702333-Figure6-1.json': 384,
 'array_fig-3120702797-Figure1-1.json': 385,
 'array_fig-3120702797-Figure10-1.json': 386,
 'array_fig-3120702797-Figure11-1.json': 387,
 'array_fig-3120702797-Figure12-1.json': 388,
 'array_fig-3120702797-Figure13-1.json': 389,
 'array_fig-3120702797-Figure14-1.json': 390,
 'array_fig-3120702797-Figure2-1.json': 391,
 'array_fig-3120702797-Figure4-1.json': 392,
 'array_fig-3120702797-Figure5-1.json': 393,
 'array_fig-3120702797-Figure6-1.json': 394,
 'array_fig-3120702797-Figure7-1.json': 395,
 'array_fig-3120702797-Figure8-1.json': 396,
 'array_fig-3120702797-Figure9-1.json': 397,
 'array_fig-3121047872-Figure1-1.json': 398,
 'array_fig-3121047872-Figure2-1.json': 399,
 'array_fig-3121047872-Figure3-1.json': 400,
 'array_fig-3121873183-Figure1-1.json': 401,
 'array_fig-3121873183-Figure10-1.json': 402,
 'array_fig-3121873183-Figure11-1.json': 403,
 'array_fig-3121873183-Figure12-1.json': 404,
 'array_fig-3121873183-Figure13-1.json': 405,
 'array_fig-3121873183-Figure14-1.json': 406,
 'array_fig-3121873183-Figure2-1.json': 407,
 'array_fig-3121873183-Figure3-1.json': 408,
 'array_fig-3121873183-Figure4-1.json': 409,
 'array_fig-3121873183-Figure5-1.json': 410,
 'array_fig-3121873183-Figure6-1.json': 411,
 'array_fig-3121873183-Figure7-1.json': 412,
 'array_fig-3121873183-Figure8-1.json': 413,
 'array_fig-3121873183-Figure9-1.json': 414,
 'array_fig-3121873183-FigureA.1-1.json': 415,
 'array_fig-3121873183-FigureA.2-1.json': 416,
 'array_fig-3121873183-FigureA.3-1.json': 417,
 'array_fig-3121873183-FigureA.4-1.json': 418,
 'array_fig-3122294042-Figure10-1.json': 419,
 'array_fig-3122294042-Figure11-1.json': 420,
 'array_fig-3122294042-Figure9-1.json': 421,
 'array_fig-3122816307-Figure1-1.json': 422,
 'array_fig-3122816307-Figure6-1.json': 423,
 'array_fig-3123154832-Figure1-1.json': 424,
 'array_fig-3123154832-Figure11-1.json': 425,
 'array_fig-3123154832-Figure12-1.json': 426,
 'array_fig-3123154832-Figure13-1.json': 427,
 'array_fig-3123154832-Figure14-1.json': 428,
 'array_fig-3123154832-Figure15-1.json': 429,
 'array_fig-3123154832-Figure16-1.json': 430,
 'array_fig-3123154832-Figure17-1.json': 431,
 'array_fig-3123154832-Figure2-1.json': 432,
 'array_fig-3123154832-Figure3-1.json': 433,
 'array_fig-3123154832-Figure4-1.json': 434,
 'array_fig-3123154832-Figure5-1.json': 435,
 'array_fig-3123154832-Figure6-1.json': 436,
 'array_fig-3123154832-Figure7-1.json': 437,
 'array_fig-3123154832-Figure8-1.json': 438,
 'array_fig-3123154832-Figure9-1.json': 439,
 'array_fig-3123954254-Figure1-1.json': 440,

In [42]:
# mystery
# why are there tons of figures listed multiple times
counter = {}
for f in figure_id_ordered_paths:
    count = counter.get(f,0)
    count+=1
    counter[f] =count
    
counter

{'array_fig-4281966491-Figure1-1.json': 2,
 'array_fig-4210714446-Figure10-1.json': 3,
 'array_fig-4210714446-Figure6-1.json': 3,
 'array_fig-4210714446-Figure1-1.json': 3,
 'array_fig-4210714446-Figure4-1.json': 3,
 'array_fig-4210714446-Figure2-1.json': 3,
 'array_fig-4210714446-Figure9-1.json': 3,
 'array_fig-4210714446-Figure7-1.json': 3,
 'array_fig-4210714446-Figure3-1.json': 3,
 'array_fig-4210714446-Figure8-1.json': 3,
 'array_fig-4210712567-Figure1-1.json': 3,
 'array_fig-4210712567-Figure4-1.json': 3,
 'array_fig-4210712567-Figure2-1.json': 3,
 'array_fig-4210712567-Figure5-1.json': 3,
 'array_fig-4210712567-Figure3-1.json': 3,
 'array_fig-4292117664-Figure1-1.json': 2,
 'array_fig-4292117664-Figure4-1.json': 2,
 'array_fig-4292117664-Figure2-1.json': 2,
 'array_fig-4226179712-Figure6-1.json': 2,
 'array_fig-4226179712-Figure1-1.json': 2,
 'array_fig-2340671844-Figure1-1.json': 2,
 'array_fig-2340671844-Figure10-1.json': 2,
 'array_fig-2340671844-Figure11-1.json': 2,
 'array_fig-2340671844-Figure12-1.json': 2,
 'array_fig-2340671844-Figure13-1.json': 2,
 'array_fig-2340671844-Figure14-1.json': 2,
 'array_fig-2340671844-Figure15-1.json': 2,
 'array_fig-2340671844-Figure16-1.json': 2,
 'array_fig-2340671844-Figure17-1.json': 2,
 'array_fig-2340671844-Figure18-1.json': 2,
 'array_fig-2340671844-Figure19-1.json': 2,
 'array_fig-2340671844-Figure2-1.json': 2,
 'array_fig-2340671844-Figure20-1.json': 2,
 'array_fig-2340671844-Figure21-1.json': 2,
 'array_fig-2340671844-Figure22-1.json': 2,
 'array_fig-2340671844-Figure23-1.json': 2,
 'array_fig-2340671844-Figure24-1.json': 2,
 'array_fig-2340671844-Figure25-1.json': 2,
 'array_fig-2340671844-Figure26-1.json': 2,
 'array_fig-2340671844-Figure27-1.json': 2,
 'array_fig-2340671844-Figure28-1.json': 2,
 'array_fig-2340671844-Figure29-1.json': 2,
 'array_fig-2340671844-Figure3-1.json': 2,
 'array_fig-2340671844-Figure30-1.json': 2,
 'array_fig-2340671844-Figure31-1.json': 2,
 'array_fig-2340671844-Figure32-1.json': 2,
 'array_fig-2340671844-Figure33-1.json': 2,
 'array_fig-2340671844-Figure36-1.json': 2,
 'array_fig-2340671844-Figure37-1.json': 2,
 'array_fig-2340671844-Figure38-1.json': 2,
 'array_fig-2340671844-Figure39-1.json': 2,
 'array_fig-2340671844-Figure4-1.json': 2,
 'array_fig-2340671844-Figure40-1.json': 2,
 'array_fig-2340671844-Figure41-1.json': 2,
 'array_fig-2340671844-Figure42-1.json': 2,
 'array_fig-2340671844-Figure43-1.json': 2,
 'array_fig-2340671844-Figure44-1.json': 2,
 'array_fig-2340671844-Figure45-1.json': 2,
 'array_fig-2340671844-Figure46-1.json': 2,
 'array_fig-2340671844-Figure48-1.json': 2,
 'array_fig-2340671844-Figure49-1.json': 2,
 'array_fig-2340671844-Figure5-1.json': 2,
 'array_fig-2340671844-Figure50-1.json': 2,
 'array_fig-2340671844-Figure51-1.json': 2,
 'array_fig-2340671844-Figure52-1.json': 2,
 'array_fig-2340671844-Figure53-1.json': 2,
 'array_fig-2340671844-Figure54-1.json': 2,
 'array_fig-2340671844-Figure55-1.json': 2,
 'array_fig-2340671844-Figure56-1.json': 2,
 'array_fig-2340671844-Figure57-1.json': 2,
 'array_fig-2340671844-Figure58-1.json': 2,
 'array_fig-2340671844-Figure59-1.json': 2,
 'array_fig-2340671844-Figure6-1.json': 2,
 'array_fig-2340671844-Figure60-1.json': 2,
 'array_fig-2340671844-Figure61-1.json': 2,
 'array_fig-2340671844-Figure62-1.json': 2,
 'array_fig-2340671844-Figure63-1.json': 2,
 'array_fig-2340671844-Figure7-1.json': 2,
 'array_fig-2340671844-Figure8-1.json': 2,
 'array_fig-2340671844-Figure9-1.json': 2,
 'array_fig-2399564276-Figure1-1.json': 2,
 'array_fig-2399564276-Figure2-1.json': 2,
 'array_fig-2399564276-Figure3-1.json': 2,
 'array_fig-2399564276-Figure4-1.json': 2,
 'array_fig-2510179618-Figure10-1.json': 2,
 'array_fig-2510179618-Figure11-1.json': 2,
 'array_fig-2510179618-Figure12-1.json': 2,
 'array_fig-2510179618-Figure13-1.json': 2,
 'array_fig-2510179618-Figure14-1.json': 2,
 'array_fig-2510179618-Figure15-1.json': 2,
 'array_fig-2510179618-Figure16-1.json': 2,
 'array_fig-2510179618-Figure17-1.json': 2,
 'array_fig-2510179618-Figure18-1.json': 2,
 'array_fig-2510179618-Figure19-1.json': 2,
 'array_fig-2510179618-Figure2-1.json': 2,
 'array_fig-2510179618-Figure20-1.json': 2,
 'array_fig-2510179618-Figure21-1.json': 2,
 'array_fig-2510179618-Figure22-1.json': 2,
 'array_fig-2510179618-Figure23-1.json': 2,
 'array_fig-2510179618-Figure24-1.json': 2,
 'array_fig-2510179618-Figure25-1.json': 2,
 'array_fig-2510179618-Figure26-1.json': 2,
 'array_fig-2510179618-Figure27-1.json': 2,
 'array_fig-2510179618-Figure28-1.json': 2,
 'array_fig-2510179618-Figure29-1.json': 2,
 'array_fig-2510179618-Figure3-1.json': 2,
 'array_fig-2510179618-Figure30-1.json': 2,
 'array_fig-2510179618-Figure31-1.json': 2,
 'array_fig-2510179618-Figure32-1.json': 2,
 'array_fig-2510179618-Figure33-1.json': 2,
 'array_fig-2510179618-Figure34-1.json': 2,
 'array_fig-2510179618-Figure35-1.json': 2,
 'array_fig-2510179618-Figure36-1.json': 2,
 'array_fig-2510179618-Figure37-1.json': 2,
 'array_fig-2510179618-Figure38-1.json': 2,
 'array_fig-2510179618-Figure39-1.json': 2,
 'array_fig-2510179618-Figure4-1.json': 2,
 'array_fig-2510179618-Figure40-1.json': 2,
 'array_fig-2510179618-Figure41-1.json': 2,
 'array_fig-2510179618-Figure42-1.json': 2,
 'array_fig-2510179618-Figure43-1.json': 2,
 'array_fig-2510179618-Figure44-1.json': 2,
 'array_fig-2510179618-Figure45-1.json': 2,
 'array_fig-2510179618-Figure46-1.json': 2,
 'array_fig-2510179618-Figure47-1.json': 2,
 'array_fig-2510179618-Figure48-1.json': 2,
 'array_fig-2510179618-Figure49-1.json': 2,
 'array_fig-2510179618-Figure5-1.json': 2,
 'array_fig-2510179618-Figure50-1.json': 2,
 'array_fig-2510179618-Figure51-1.json': 2,
 'array_fig-2510179618-Figure52-1.json': 2,
 'array_fig-2510179618-Figure53-1.json': 2,
 'array_fig-2510179618-Figure54-1.json': 2,
 'array_fig-2510179618-Figure55-1.json': 2,
 'array_fig-2510179618-Figure56-1.json': 2,
 'array_fig-2510179618-Figure57-1.json': 2,
 'array_fig-2510179618-Figure58-1.json': 2,
 'array_fig-2510179618-Figure59-1.json': 2,
 'array_fig-2510179618-Figure6-1.json': 2,
 'array_fig-2510179618-Figure60-1.json': 2,
 'array_fig-2510179618-Figure61-1.json': 2,
 'array_fig-2510179618-Figure62-1.json': 2,
 'array_fig-2510179618-Figure63-1.json': 2,
 'array_fig-2510179618-Figure64-1.json': 2,
 'array_fig-2510179618-Figure65-1.json': 2,
 'array_fig-2510179618-Figure66-1.json': 2,
 'array_fig-2510179618-Figure67-1.json': 2,
 'array_fig-2510179618-Figure68-1.json': 2,
 'array_fig-2510179618-Figure69-1.json': 2,
 'array_fig-2510179618-Figure7-1.json': 2,
 'array_fig-2510179618-Figure8-1.json': 2,
 'array_fig-2510179618-Figure9-1.json': 2,
 'array_fig-2516782548-Figure1-1.json': 2,
 'array_fig-2516782548-Figure2-1.json': 2,
 'array_fig-2516782548-Figure3-1.json': 2,
 'array_fig-2516782548-Figure4-1.json': 2,
 'array_fig-2516782548-Figure5-1.json': 2,
 'array_fig-2883397413-Figure1-1.json': 2,
 'array_fig-2903984611-Figure2-1.json': 2,
 'array_fig-2917246580-Figure1-1.json': 2,
 'array_fig-2917246580-Figure10-1.json': 2,
 'array_fig-2917246580-Figure11-1.json': 2,
 'array_fig-2917246580-Figure2-1.json': 2,
 'array_fig-2917246580-Figure3-1.json': 2,
 'array_fig-2917246580-Figure4-1.json': 2,
 'array_fig-2917246580-Figure5-1.json': 2,
 'array_fig-2917246580-Figure6-1.json': 2,
 'array_fig-2917246580-Figure7-1.json': 2,
 'array_fig-2917246580-Figure8-1.json': 2,
 'array_fig-2917246580-Figure9-1.json': 2,
 'array_fig-2948579940-Figure1-1.json': 2,
 'array_fig-2948579940-Figure2-1.json': 2,
 'array_fig-2948579940-Figure3-1.json': 2,
 'array_fig-2953880153-Figure1-1.json': 2,
 'array_fig-2953880153-Figure2-1.json': 2,
 'array_fig-2953880153-Figure3-1.json': 2,
 'array_fig-2953880153-Figure4-1.json': 2,
 'array_fig-2953880153-Figure5-1.json': 2,
 'array_fig-2953880153-Figure6-1.json': 2,
 'array_fig-2953880153-Figure7-1.json': 2,
 'array_fig-2953880153-Figure8-1.json': 2,
 'array_fig-2978782546-Figure1-1.json': 2,
 'array_fig-2978782546-Figure2-1.json': 2,
 'array_fig-2978782546-Figure3-1.json': 2,
 'array_fig-2978782546-Figure4-1.json': 2,
 'array_fig-2980000635-Figure1-1.json': 2,
 'array_fig-2980000635-Figure2-1.json': 2,
 'array_fig-2980000635-Figure3-1.json': 2,
 'array_fig-2980000635-Figure5-1.json': 2,
 'array_fig-2980000635-Figure6-1.json': 2,
 'array_fig-2982324007-Figure2-1.json': 2,
 'array_fig-2982324007-Figure3-1.json': 2,
 'array_fig-2982324007-Figure4-1.json': 2,
 'array_fig-2982324007-Figure5-1.json': 2,
 'array_fig-2982333300-Figure1-1.json': 2,
 'array_fig-2982333300-Figure10-1.json': 2,
 'array_fig-2982333300-Figure11-1.json': 2,
 'array_fig-2982333300-Figure12-1.json': 2,
 'array_fig-2982333300-Figure13-1.json': 2,
 'array_fig-2982333300-Figure14-1.json': 2,
 'array_fig-2982333300-Figure15-1.json': 2,
 'array_fig-2982333300-Figure16-1.json': 2,
 'array_fig-2982333300-Figure17-1.json': 2,
 'array_fig-2982333300-Figure18-1.json': 2,
 'array_fig-2982333300-Figure2-1.json': 2,
 'array_fig-2982333300-Figure3-1.json': 2,
 'array_fig-2982333300-Figure4-1.json': 2,
 'array_fig-2982333300-Figure5-1.json': 2,
 'array_fig-2982333300-Figure6-1.json': 2,
 'array_fig-2982333300-Figure7-1.json': 2,
 'array_fig-2982333300-Figure8-1.json': 2,
 'array_fig-2982333300-Figure9-1.json': 2,
 'array_fig-2989360195-Figure1-1.json': 2,
 'array_fig-2989360195-Figure2-1.json': 2,
 'array_fig-2989360195-Figure3-1.json': 2,
 'array_fig-2989360195-Figure4-1.json': 2,
 'array_fig-2997451176-Figure1-1.json': 2,
 'array_fig-2997451176-Figure2-1.json': 2,
 'array_fig-3000625380-Figure5-1.json': 2,
 'array_fig-3004250597-Figure1-1.json': 2,
 'array_fig-3004250597-Figure2-1.json': 2,
 'array_fig-3004250597-Figure3-1.json': 2,
 'array_fig-3004250597-Figure4-1.json': 2,
 'array_fig-3004250597-Figure5-1.json': 2,
 'array_fig-3005576178-Figure1-1.json': 2,
 'array_fig-3005576178-Figure2-1.json': 2,
 'array_fig-3008463181-Figure1-1.json': 2,
 'array_fig-3008463181-Figure10-1.json': 2,
 'array_fig-3008463181-Figure2-1.json': 2,
 'array_fig-3008463181-Figure3-1.json': 2,
 'array_fig-3008463181-Figure4-1.json': 2,
 'array_fig-3008463181-Figure5-1.json': 2,
 'array_fig-3008463181-Figure6-1.json': 2,
 'array_fig-3008463181-Figure7-1.json': 2,
 'array_fig-3008463181-Figure8-1.json': 2,
 'array_fig-3008463181-Figure9-1.json': 2,
 'array_fig-3009522687-Figure1-1.json': 2,
 'array_fig-3009522687-Figure2-1.json': 2,
 'array_fig-3009742497-Figure1-1.json': 2,
 'array_fig-3009742497-Figure2-1.json': 2,
 'array_fig-3009742497-Figure3-1.json': 2,
 'array_fig-3009742497-Figure4-1.json': 2,
 'array_fig-3009742497-Figure5-1.json': 2,
 'array_fig-3009742497-Figure6-1.json': 2,
 'array_fig-3009742497-Figure7-1.json': 2,
 'array_fig-3009742497-Figure8-1.json': 2,
 'array_fig-3009742497-Figure9-1.json': 2,
 'array_fig-3011923337-Figure1-1.json': 2,
 'array_fig-3011923337-Figure2-1.json': 2,
 'array_fig-3011923337-Figure3-1.json': 2,
 'array_fig-3013671361-Figure1-1.json': 2,
 'array_fig-3013671361-Figure2-1.json': 2,
 'array_fig-3018002705-Figure1-1.json': 2,
 'array_fig-3018002705-Figure2-1.json': 2,
 'array_fig-3018002705-Figure3-1.json': 2,
 'array_fig-3018002705-Figure4-1.json': 2,
 'array_fig-3018002705-Figure5-1.json': 2,
 'array_fig-3018002705-Figure6-1.json': 2,
 'array_fig-3021385523-Figure1-1.json': 2,
 'array_fig-3021385523-Figure2-1.json': 2,
 'array_fig-3021385523-Figure3-1.json': 2,
 'array_fig-3021385523-Figure4-1.json': 2,
 'array_fig-3021385523-Figure5-1.json': 2,
 'array_fig-3022153899-Figure1-1.json': 2,
 'array_fig-3035183408-Figure1-1.json': 2,
 'array_fig-3036075322-Figure1-1.json': 2,
 'array_fig-3036075322-Figure2-1.json': 2,
 'array_fig-3036075322-Figure3-1.json': 2,
 'array_fig-3036075322-Figure4-1.json': 2,
 'array_fig-3036370159-Figure1-1.json': 2,
 'array_fig-3036370159-Figure2-1.json': 2,
 'array_fig-3036370159-Figure3-1.json': 2,
 'array_fig-3036370159-Figure5-1.json': 2,
 'array_fig-3038093235-Figure1-1.json': 2,
 'array_fig-3038093235-Figure10-1.json': 2,
 'array_fig-3038093235-Figure11-1.json': 2,
 'array_fig-3038093235-Figure16-1.json': 2,
 'array_fig-3038093235-Figure2-1.json': 2,
 'array_fig-3038093235-Figure22-1.json': 2,
 'array_fig-3038093235-Figure3-1.json': 2,
 'array_fig-3038093235-Figure4-1.json': 2,
 'array_fig-3038093235-Figure5-1.json': 2,
 'array_fig-3038093235-Figure6-1.json': 2,
 'array_fig-3038093235-Figure7-1.json': 2,
 'array_fig-3038093235-Figure8-1.json': 2,
 'array_fig-3038093235-Figure9-1.json': 2,
 'array_fig-3041392591-Figure1-1.json': 2,
 'array_fig-3041392591-Figure10-1.json': 2,
 'array_fig-3041392591-Figure2-1.json': 2,
 'array_fig-3041392591-Figure3-1.json': 2,
 'array_fig-3041392591-Figure4-1.json': 2,
 'array_fig-3041392591-Figure5-1.json': 2,
 'array_fig-3041392591-Figure6-1.json': 2,
 'array_fig-3041392591-Figure7-1.json': 2,
 'array_fig-3041392591-Figure8-1.json': 2,
 'array_fig-3041392591-Figure9-1.json': 2,
 'array_fig-3043392521-Figure1-1.json': 2,
 'array_fig-3043392521-Figure2-1.json': 2,
 'array_fig-3044968142-Figure1-1.json': 2,
 'array_fig-3044968142-Figure2-1.json': 2,
 'array_fig-3044968142-Figure3-1.json': 2,
 'array_fig-3044968142-Figure4-1.json': 2,
 'array_fig-3044968142-Figure5-1.json': 2,
 'array_fig-3044968142-Figure6-1.json': 2,
 'array_fig-3044968142-Figure7-1.json': 2,
 'array_fig-3048426687-Figure1-1.json': 2,
 'array_fig-3052291153-Figure1-1.json': 2,
 'array_fig-3080826078-Figure1-1.json': 2,
 'array_fig-3080826078-Figure10-1.json': 2,
 'array_fig-3080826078-Figure11-1.json': 2,
 'array_fig-3080826078-Figure12-1.json': 2,
 'array_fig-3080826078-Figure13-1.json': 2,
 'array_fig-3080826078-Figure14-1.json': 2,
 'array_fig-3080826078-Figure15-1.json': 2,
 'array_fig-3080826078-Figure2-1.json': 2,
 'array_fig-3080826078-Figure4-1.json': 2,
 'array_fig-3080826078-Figure8-1.json': 2,
 'array_fig-3080826078-Figure9-1.json': 2,
 'array_fig-3082127980-Figure1-1.json': 2,
 'array_fig-3082127980-Figure2-1.json': 2,
 'array_fig-3082127980-Figure3-1.json': 2,
 'array_fig-3082127980-Figure4-1.json': 2,
 'array_fig-3082127980-Figure5-1.json': 2,
 'array_fig-3082127980-Figure6-1.json': 2,
 'array_fig-3082127980-Figure7-1.json': 2,
 'array_fig-3082127980-Figure8-1.json': 2,
 'array_fig-3084143938-Figure1-1.json': 2,
 'array_fig-3084143938-Figure2-1.json': 2,
 'array_fig-3084143938-Figure3-1.json': 2,
 'array_fig-3090924138-Figure1-1.json': 2,
 'array_fig-3090924138-Figure3-1.json': 2,
 'array_fig-3092500000-Figure1-1.json': 2,
 'array_fig-3092500000-Figure2-1.json': 2,
 'array_fig-3092500000-Figure3-1.json': 2,
 'array_fig-3092500000-Figure4-1.json': 2,
 'array_fig-3093650263-Figure1-1.json': 2,
 'array_fig-3093650263-Figure2-1.json': 2,
 'array_fig-3093650263-Figure3-1.json': 2,
 'array_fig-3093650263-Figure4-1.json': 2,
 'array_fig-3094513744-Figure1-1.json': 2,
 'array_fig-3095647601-Figure1-1.json': 2,
 'array_fig-3095647601-Figure2-1.json': 2,
 'array_fig-3095647601-Figure3-1.json': 2,
 'array_fig-3095647601-Figure5-1.json': 2,
 'array_fig-3095647601-Figure6-1.json': 2,
 'array_fig-3095682039-Figure1-1.json': 2,
 'array_fig-3095682039-Figure10-1.json': 2,
 'array_fig-3095682039-Figure11-1.json': 2,
 'array_fig-3095682039-Figure12-1.json': 2,
 'array_fig-3095682039-Figure13-1.json': 2,
 'array_fig-3095682039-Figure14-1.json': 2,
 'array_fig-3095682039-Figure15-1.json': 2,
 'array_fig-3095682039-Figure16-1.json': 2,
 'array_fig-3095682039-Figure17-1.json': 2,
 'array_fig-3095682039-Figure18-1.json': 2,
 'array_fig-3095682039-Figure2-1.json': 2,
 'array_fig-3095682039-Figure3-1.json': 2,
 'array_fig-3095682039-Figure4-1.json': 2,
 'array_fig-3095682039-Figure5-1.json': 2,
 'array_fig-3095682039-Figure6-1.json': 2,
 'array_fig-3095682039-Figure7-1.json': 2,
 'array_fig-3095682039-Figure8-1.json': 2,
 'array_fig-3095682039-Figure9-1.json': 2,
 'array_fig-3095925971-Figure1-1.json': 2,
 'array_fig-3096572172-Figure1.1-1.json': 2,
 'array_fig-3096572172-Figure1.10-1.json': 2,
 'array_fig-3096572172-Figure1.11-1.json': 2,
 'array_fig-3096572172-Figure1.12-1.json': 2,
 'array_fig-3096572172-Figure1.2-1.json': 2,
 'array_fig-3096572172-Figure1.3-1.json': 2,
 'array_fig-3096572172-Figure1.4-1.json': 2,
 'array_fig-3096572172-Figure1.5-1.json': 2,
 'array_fig-3096572172-Figure1.6-1.json': 2,
 'array_fig-3096572172-Figure1.7-1.json': 2,
 'array_fig-3096572172-Figure1.8-1.json': 2,
 'array_fig-3096572172-Figure1.9-1.json': 2,
 'array_fig-3098718496-Figure2-1.json': 2,
 'array_fig-3098718496-Figure4-1.json': 2,
 'array_fig-3111728169-Figure11-1.json': 2,
 'array_fig-3111728169-Figure12-1.json': 2,
 'array_fig-3111728169-Figure13-1.json': 2,
 'array_fig-3111728169-Figure7-1.json': 2,
 'array_fig-3111728169-Figure8-1.json': 2,
 'array_fig-3111728169-Figure9-1.json': 2,
 'array_fig-3120336817-Figure1.1-1.json': 2,
 'array_fig-3120336817-Figure1.10-1.json': 2,
 'array_fig-3120336817-Figure1.11-1.json': 2,
 'array_fig-3120336817-Figure1.12-1.json': 2,
 'array_fig-3120336817-Figure1.13-1.json': 2,
 'array_fig-3120336817-Figure1.14-1.json': 2,
 'array_fig-3120336817-Figure1.15-1.json': 2,
 'array_fig-3120336817-Figure1.16-1.json': 2,
 'array_fig-3120336817-Figure1.2-1.json': 2,
 'array_fig-3120336817-Figure1.3-1.json': 2,
 'array_fig-3120336817-Figure1.4-1.json': 2,
 'array_fig-3120336817-Figure1.5-1.json': 2,
 'array_fig-3120336817-Figure1.6-1.json': 2,
 'array_fig-3120336817-Figure1.7-1.json': 2,
 'array_fig-3120336817-Figure1.8-1.json': 2,
 'array_fig-3120336817-Figure1.9-1.json': 2,
 'array_fig-3120702333-Figure1-1.json': 2,
 'array_fig-3120702333-Figure2-1.json': 2,
 'array_fig-3120702333-Figure3-1.json': 2,
 'array_fig-3120702333-Figure5-1.json': 2,
 'array_fig-3120702333-Figure6-1.json': 2,
 'array_fig-3120702797-Figure1-1.json': 2,
 'array_fig-3120702797-Figure10-1.json': 2,
 'array_fig-3120702797-Figure11-1.json': 2,
 'array_fig-3120702797-Figure12-1.json': 2,
 'array_fig-3120702797-Figure13-1.json': 2,
 'array_fig-3120702797-Figure14-1.json': 2,
 'array_fig-3120702797-Figure2-1.json': 2,
 'array_fig-3120702797-Figure4-1.json': 2,
 'array_fig-3120702797-Figure5-1.json': 2,
 'array_fig-3120702797-Figure6-1.json': 2,
 'array_fig-3120702797-Figure7-1.json': 2,
 'array_fig-3120702797-Figure8-1.json': 2,
 'array_fig-3120702797-Figure9-1.json': 2,
 'array_fig-3121047872-Figure1-1.json': 2,
 'array_fig-3121047872-Figure2-1.json': 2,
 'array_fig-3121047872-Figure3-1.json': 2,
 'array_fig-3121873183-Figure1-1.json': 2,
 'array_fig-3121873183-Figure10-1.json': 2,
 'array_fig-3121873183-Figure11-1.json': 2,
 'array_fig-3121873183-Figure12-1.json': 2,
 'array_fig-3121873183-Figure13-1.json': 2,
 'array_fig-3121873183-Figure14-1.json': 2,
 'array_fig-3121873183-Figure2-1.json': 2,
 'array_fig-3121873183-Figure3-1.json': 2,
 'array_fig-3121873183-Figure4-1.json': 2,
 'array_fig-3121873183-Figure5-1.json': 2,
 'array_fig-3121873183-Figure6-1.json': 2,
 'array_fig-3121873183-Figure7-1.json': 2,
 'array_fig-3121873183-Figure8-1.json': 2,
 'array_fig-3121873183-Figure9-1.json': 2,
 'array_fig-3121873183-FigureA.1-1.json': 2,
 'array_fig-3121873183-FigureA.2-1.json': 2,
 'array_fig-3121873183-FigureA.3-1.json': 2,
 'array_fig-3121873183-FigureA.4-1.json': 2,
 'array_fig-3122294042-Figure10-1.json': 2,
 'array_fig-3122294042-Figure11-1.json': 2,
 'array_fig-3122294042-Figure9-1.json': 2,
 'array_fig-3122816307-Figure1-1.json': 2,
 'array_fig-3122816307-Figure6-1.json': 2,
 'array_fig-3123154832-Figure1-1.json': 2,
 'array_fig-3123154832-Figure11-1.json': 2,
 'array_fig-3123154832-Figure12-1.json': 2,
 'array_fig-3123154832-Figure13-1.json': 2,
 'array_fig-3123154832-Figure14-1.json': 2,
 'array_fig-3123154832-Figure15-1.json': 2,
 'array_fig-3123154832-Figure16-1.json': 2,
 'array_fig-3123154832-Figure17-1.json': 2,
 'array_fig-3123154832-Figure2-1.json': 2,
 'array_fig-3123154832-Figure3-1.json': 2,
 'array_fig-3123154832-Figure4-1.json': 2,
 'array_fig-3123154832-Figure5-1.json': 2,
 'array_fig-3123154832-Figure6-1.json': 2,
 'array_fig-3123154832-Figure7-1.json': 2,
 'array_fig-3123154832-Figure8-1.json': 2,

In [8]:
embedding = np.load("./embedded_chart_types_15_2d.npy")

In [9]:
fig_prop_df = connection.sql("SELECT * FROM figure_property").df()

fig_prop_df


# this removes any of the missing figures so that we update just the correct ones
fig_prop_df[exists_check]

# entirely possible that the updates are going to be easier as pandas instead of duckdb 

# demonstration of reordering based on indexing

rand_test = (np.random.random((15,3))*10).astype("uint8")

rand_test

inds = np.random.choice(np.arange(15),15,replace=False)

inds

rand_test[inds]

array_indices = [lookup_map[fig_path] for i,fig_path in enumerate(figure_id_ordered_paths) if exists_check[i] ]
array_indices

table_ordered_embeddings = embedding[array_indices]
table_ordered_embeddings

array([[ 33.39754 ,  20.890371],
       [ 52.282734, -60.680984],
       [ 34.247505,  56.440586],
       ...,
       [ 19.96133 , -46.644093],
       [ 96.64834 , -46.418762],
       [ 68.81347 ,  10.035036]], dtype=float32)

In [53]:
array_indices

array([6217, 2877, 2881, ..., 9997, 9998, 9999])

In [54]:
arrays[array_indices[0]]

PosixPath('outputs/array_fig-4281966491-Figure1-1.json')

In [38]:
table_ordered_embeddings.shape

(12911, 2)

In [37]:
embedding.shape

(10000, 2)

In [35]:
array_indices.shape

(12911,)

In [33]:
table_ordered_embeddings.shape

(12911, 2)

In [39]:
len(exists_check)

14486

In [40]:
sum(exists_check)

12911

In [10]:
array_indices

[6217,
 2877,
 2881,
 2876,
 2880,
 2878,
 2884,
 2882,
 2879,
 2883,
 2871,
 2874,
 2872,
 2875,
 2873,
 7776,
 7778,
 7777,
 5350,
 5345,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 ...]

In [43]:
np.column_stack([np.array(array_indices)[:,None],table_ordered_embeddings])

array([[6217.        ,   33.39754105,   20.89037132],
       [2877.        ,   52.28273392,  -60.6809845 ],
       [2881.        ,   34.24750519,   56.44058609],
       ...,
       [9997.        ,   19.96133041,  -46.64409256],
       [9998.        ,   96.64833832,  -46.41876221],
       [9999.        ,   68.81346893,   10.03503609]])

In [18]:
import pandas as pd

In [61]:
og_df  = connection.sql("SELECT * FROM figure_property").df()

In [62]:
og_df

,figure_id,name,int_value,string_value,xPos,yPos,zPos,score
0,0,name-1,1,uigXfXok,0.188985,13.698142,-10.303946,2760
1,1,name-42,42,LrgopzrG,8.893129,8.880141,9.741223,81195
2,2,name-4,4,MXeDVNQU,6.284884,10.211571,4.502829,77555
3,3,name-6,6,hYUFJQMX,7.729008,4.585903,-9.169049,85731
4,4,name-3,3,oNTzMXQF,25.651455,9.985393,-1.703986,47666
...,...,...,...,...,...,...,...,...
14481,14481,name-14,14,kaAvZsLf,-1105.000000,87.000000,-390.000000,58555
14482,14482,name-41,41,zxjZmkcU,-895.000000,65.000000,695.000000,43870
14483,14483,name-19,19,qAkCGvny,720.000000,3.000000,-240.000000,2382
14484,14484,name-19,19,EVAYXLry,540.000000,87.000000,-375.000000,58663
14485,14485,name-32,32,EzQxWIKt,-955.000000,146.000000,200.000000,97737

In [64]:
len(exists_check)

14486

In [63]:
og_df.loc[exists_check,]

,figure_id,name,int_value,string_value,xPos,yPos,zPos,score
0,0,name-1,1,uigXfXok,0.188985,13.698142,-10.303946,2760
1,1,name-42,42,LrgopzrG,8.893129,8.880141,9.741223,81195
2,2,name-4,4,MXeDVNQU,6.284884,10.211571,4.502829,77555
3,3,name-6,6,hYUFJQMX,7.729008,4.585903,-9.169049,85731
4,4,name-3,3,oNTzMXQF,25.651455,9.985393,-1.703986,47666
...,...,...,...,...,...,...,...,...
12906,12906,name-13,13,XxgvlxIs,-7.725756,6.583314,10.997828,30096
12907,12907,name-26,26,hzlXrbLS,7.837799,5.933046,11.120034,16127
12908,12908,name-22,22,DtEsuSar,-14.693877,-9.589152,4.078270,52773
12909,12909,name-7,7,lnamOXhQ,18.914112,-10.648349,-5.735243,75086
12910,12910,name-28,28,kbxGJTep,3.192539,-10.773570,-4.710289,85725

In [ ]:
duckdb.sql("CREATE TABLE 2d_tsne AS SELECT * FROM my_df")

In [65]:
duckdb.close()

In [66]:
connection = db.connect("test.db")

In [67]:
connection.sql("SHOW TABLES")

┌─────────────────┐
│      name       │
│     varchar     │
├─────────────────┤
│ author          │
│ charts          │
│ contribution    │
│ figure          │
│ figure_property │
│ institution     │
│ keyword         │
│ paper           │
│ residence       │
│ topic           │
│ work_keyword    │
│ work_topic      │
├─────────────────┤
│     12 rows     │
└─────────────────┘

In [68]:
table_ordered_embeddings

array([[ 33.39754 ,  20.890371],
       [ 52.282734, -60.680984],
       [ 34.247505,  56.440586],
       ...,
       [ 19.96133 , -46.644093],
       [ 96.64834 , -46.418762],
       [ 68.81347 ,  10.035036]], dtype=float32)

In [72]:
connection.sql("SELECT * FROM figure_property")

┌───────────┬─────────┬───────────┬──────────────┬───────┬───────┬───────┬───────┐
│ figure_id │  name   │ int_value │ string_value │ xPos  │ yPos  │ zPos  │ score │
│   int64   │ varchar │   int32   │   varchar    │ int32 │ int32 │ int32 │ int32 │
├───────────┼─────────┼───────────┼──────────────┼───────┼───────┼───────┼───────┤
│         0 │ name-1  │         1 │ uigXfXok     │     0 │     0 │  -895 │  2760 │
│         1 │ name-42 │        42 │ LrgopzrG     │     0 │     0 │   860 │ 81195 │
│         2 │ name-4  │         4 │ MXeDVNQU     │     0 │     0 │ -1075 │ 77555 │
│         3 │ name-6  │         6 │ hYUFJQMX     │     0 │     0 │ -1075 │ 85731 │
│         4 │ name-3  │         3 │ oNTzMXQF     │     0 │     0 │ -1000 │ 47666 │
│         5 │ name-24 │        24 │ FHBvveQu     │     0 │     0 │    65 │  7111 │
│         6 │ name-24 │        24 │ ZHmcbpIU     │     0 │     0 │     5 │ 31565 │
│         7 │ name-30 │        30 │ sPmAjulQ     │     0 │     0 │   190 │ 87449 │
│         8 │ name-31 │        31 │ RFnqnLmm     │     0 │     0 │   295 │ 42445 │
│         9 │ name-35 │        35 │ ICSmYTGH     │     0 │     0 │   675 │ 22716 │
│         · │    ·    │         · │    ·         │     · │     · │    ·  │   ·   │
│         · │    ·    │         · │    ·         │     · │     · │    ·  │   ·   │
│         · │    ·    │         · │    ·         │     · │     · │    ·  │   ·   │
│      9990 │ name-38 │        38 │ CRhzCtxw     │     0 │     0 │   555 │ 70776 │
│      9991 │ name-21 │        21 │ PqVRoPKN     │     0 │     0 │  -130 │ 85782 │
│      9992 │ name-16 │        16 │ MOwdzNzy     │     0 │     0 │  -255 │ 11176 │
│      9993 │ name-30 │        30 │ pxdMCtFI     │     0 │     0 │   205 │ 82577 │
│      9994 │ name-35 │        35 │ AteAOhJq     │     0 │     0 │   540 │ 77624 │
│      9995 │ name-28 │        28 │ ABQBtskm     │     0 │     0 │   235 │ 65441 │
│      9996 │ name-21 │        21 │ aXDDRlFr     │     0 │     0 │     5 │ 40457 │
│      9997 │ name-36 │        36 │ ygMOhheV     │     0 │     0 │   630 │ 39331 │
│      9998 │ name-38 │        38 │ VOKLOGPz     │     0 │     0 │   600 │ 54503 │
│      9999 │ name-34 │        34 │ RSFAaJbO     │     0 │     0 │   305 │ 52301 │
├───────────┴─────────┴───────────┴──────────────┴───────┴───────┴───────┴───────┤
│ ? rows (>9999 rows, 20 shown)                                        8 columns │
└────────────────────────────────────────────────────────────────────────────────┘

In [71]:
for i,row in enumerate(table_ordered_embeddings):
    x,y = row
    connection.sql(f"UPDATE figure_property SET xPos = {0} WHERE figure_id = {i} ")
    connection.sql(f"UPDATE figure_property SET yPos = {0} WHERE figure_id = {i} ")

In [94]:
connection.close()

In [78]:
connection = db.connect("test.db")

In [79]:
connection.sql("CHECKPOINT")

FatalException: FATAL Error: Failed to create checkpoint because of error: INTERNAL Error: Unsupported compression function type

In [117]:
connection = db.connect("test.db")

In [118]:
connection.sql("SHOW TABLES").df()

               name
0            author
1            charts
2      contribution
3            figure
4   figure_property
5       institution
6           keyword
7             paper
8         residence
9             topic
10     work_keyword
11       work_topic

In [119]:
for tbl in connection.sql("SHOW TABLES").df().name:
    if tbl == "charts" or tbl == "work_keyword" or tbl == "work_topic":
        continue
    print(tbl)
    connection.sql(f"COPY {tbl} TO '{tbl}.csv' (HEADER, DELIMITER ',');")

author
contribution
figure
figure_property
institution
keyword
paper
residence
topic

In [123]:
new_con = db.connect("new.db")

In [128]:
for tbl in connection.sql("SHOW TABLES").df().name:
    if tbl == "charts" or tbl == "work_keyword" or tbl == "work_topic":
        continue
    print(tbl)
    new_con.sql(f"CREATE TABLE {tbl} AS SELECT * FROM read_csv('{tbl}.csv', AUTO_DETECT=TRUE);")

author
contribution
figure
figure_property
institution
keyword
paper
residence
topic

In [129]:
new_con.sql("SHOW TABLES")

┌─────────────────┐
│      name       │
│     varchar     │
├─────────────────┤
│ author          │
│ contribution    │
│ figure          │
│ figure_property │
│ institution     │
│ keyword         │
│ paper           │
│ residence       │
│ topic           │
└─────────────────┘

In [130]:
[print(new_con.sql(f"DESCRIBE TABLE {tbl}")) for tbl in new_con.sql("SHOW TABLES").df().name]

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id          │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ name        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ au_id       │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ paper_id    │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id          │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ paper_id    │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ local_path  │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ server_path │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

┌──────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name  │ column_type │  null   │   key   │ default │  extra  │
│   varchar    │   varchar   │ varchar │ varchar │ varchar │ varchar │
├──────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ figure_id    │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ name         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ int_value    │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ string_value │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ xPos         │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ yPos         │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ zPos         │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ score        │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└──────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id          │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ ror         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ name        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id          │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ keyword     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

┌──────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│   column_name    │ column_type │  null   │   key   │ default │  extra  │
│     varchar      │   varchar   │ varchar │ varchar │ varchar │ varchar │
├──────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id               │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ title            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ doi              │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ publication_date │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ oa_url           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ pdf_path         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ inst_id          │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ primary_topic_id │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└──────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ au_id       │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ inst_id     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id          │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ name        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ subfield    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ field       │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ domain      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

[None, None, None, None, None, None, None, None, None]

In [122]:
connection.sql("DESCRIBE TABLE work_keyword")

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id          │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ work_id     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ keyword_id  │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ score       │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [121]:
connection.sql("DESCRIBE TABLE charts")

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id          │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ chart       │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ xPos        │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ yPos        │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ zPos        │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [120]:
connection.sql("DESCRIBE TABLE work_topic")

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id          │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ work_id     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ topic_id    │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ score       │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [116]:
connection.close()

In [89]:
!wget "https://zhiyangwang.site/vis-sieve/_file/data/publications_princeton.36608975.db"

/bin/bash: wget: command not found

In [131]:
table_ordered_embeddings

array([[ 33.39754 ,  20.890371],
       [ 52.282734, -60.680984],
       [ 34.247505,  56.440586],
       ...,
       [ 19.96133 , -46.644093],
       [ 96.64834 , -46.418762],
       [ 68.81347 ,  10.035036]], dtype=float32)

In [133]:
og_df.describe()

,figure_id,int_value,xPos,yPos,zPos,score
count,14486.000000,14486.000000,14486.000000,14486.000000,14486.000000,14486.000000
mean,7242.500000,22.022643,-2.311886,8.004975,-12.791814,50105.899213
std,4181.892335,12.876033,206.565075,29.192617,201.710815,29007.057800
min,0.000000,0.000000,-1120.000000,-26.448812,-1120.000000,12.000000
25%,3621.250000,11.000000,-9.987364,-6.293885,-9.056345,25115.500000
50%,7242.500000,22.000000,-0.982851,1.461141,-0.044043,50066.500000
75%,10863.750000,33.000000,9.178718,9.904573,8.333774,75576.250000
max,14485.000000,44.000000,1095.000000,150.000000,1055.000000,99996.000000

In [134]:
len(array_indices)

12911

In [135]:
og_df[:len(array_indices)].describe()

,figure_id,int_value,xPos,yPos,zPos,score
count,12911.000000,12911.000000,12911.000000,12911.000000,12911.000000,12911.000000
mean,6455.000000,22.014639,0.199444,-0.217329,-0.334383,50045.166292
std,3727.228998,12.886414,11.682908,9.832524,10.179600,28976.881180
min,0.000000,0.000000,-22.817026,-26.448812,-26.517918,12.000000
25%,3227.500000,11.000000,-8.510283,-7.435060,-7.735101,25087.000000
50%,6455.000000,22.000000,-0.915122,-0.010774,0.180804,50039.000000
75%,9682.500000,33.000000,8.016684,7.370668,7.470092,75476.000000
max,12910.000000,44.000000,29.542242,22.441153,24.401154,99996.000000

In [136]:
new_con.close()